const http = require('node:http'), fs = require('node:fs'), path = require('node:path');
const PORT = process.argv[2] || '9333', OUT = process.argv[3] || '.';
const Q = `JSON.stringify((() => { const out = {}; try { const c = document.createElement('canvas'); const g = c.getContext('webgl2') || c.getContext('webgl'); const d = g.getExtension('WEBGL_debug_renderer_info'); out.renderer = d ? g.getParameter(d.UNMASKED_RENDERER_WEBGL) : g.getParameter(g.RENDERER); } catch (e) { out.renderer = 'err ' + e.message; } out.heapMB = performance.memory ? Math.round(performance.memory.usedJSHeapSize / 1048576) : -1; out.nodes = document.querySelectorAll('*').length; out.videos = [...document.querySelectorAll('video')].map(v => (v.className || v.id || 'v').slice(0, 20) + (v.paused ? '' : ' playing')).slice(0, 6); out.animations = document.getAnimations ? document.getAnimations().length : -1; const v = window.PinePipPanel && window.PinePipPanel.viz && window.PinePipPanel.viz(); out.vizFps = v ? Math.round(v.fps || 0) : null; out.vizQuality = v && v.renderer ? v.renderer.quality : null; out.dpr = window.devicePixelRatio; return out; })())`;
const RAF = `new Promise(r => { let n = 0; const t0 = performance.now(); const f = () => { n++; if (performance.now() - t0 < 2000) requestAnimationFrame(f); else { const v = window.PinePipPanel && window.PinePipPanel.viz && window.PinePipPanel.viz(); const c = document.querySelector('#pine-pip-panel .pip-bg canvas'); r(JSON.stringify({ rafIn2s: n, visibility: document.visibilityState, focus: document.hasFocus(), canvasRect: c ? [Math.round(c.getBoundingClientRect().left), Math.round(c.getBoundingClientRect().top)] : null, viewport: [innerWidth, innerHeight], manager: v ? Object.fromEntries(Object.entries(v).filter(([k, x]) => ['boolean', 'number', 'string'].includes(typeof x)).slice(0, 24)) : null, telemetry: window.PinePipPanel && window.PinePipPanel.telemetry ? 'has telemetry()' : 'none' })); } }; requestAnimationFrame(f); })`;
const LONGTASK = `new Promise(r => { const t0 = performance.now(); let n = 0; const tick = () => { n++; if (performance.now() - t0 < 2000) setTimeout(tick, 0); else r(JSON.stringify({ timerTurnsIn2s: n, msPerTurn: (2000 / n).toFixed(1) })); }; setTimeout(tick, 0); })`;
http.get({ host: '127.0.0.1', port: Number(PORT), path: '/json', timeout: 5000 }, res => { let b = ''; res.on('data', d => { b += d; }); res.on('end', async () => {
  const t = JSON.parse(b).find(x => /8096/.test(x.url || ''));
  const ws = new WebSocket(t.webSocketDebuggerUrl); let id = 0; const waiting = new Map();
  ws.onmessage = ev => { const m = JSON.parse(ev.data); if (m.id && waiting.has(m.id)) { waiting.get(m.id)(m); waiting.delete(m.id); } };
  const send = (method, params = {}) => new Promise(r => { const n = ++id; waiting.set(n, r); ws.send(JSON.stringify({ id: n, method, params })); });
  await new Promise((r, j) => { ws.onopen = r; ws.onerror = () => j(new Error('socket')); setTimeout(() => j(new Error('timeout')), 15000); });
  const a = await send('Runtime.evaluate', { expression: Q, returnByValue: true }); console.log('live page:', a.result && a.result.result && a.result.result.value);
  const b2 = await send('Runtime.evaluate', { expression: LONGTASK, awaitPromise: true, returnByValue: true }); console.log('main thread:', b2.result && b2.result.result && b2.result.result.value);
  const b3 = await send('Runtime.evaluate', { expression: RAF, awaitPromise: true, returnByValue: true }); console.log('raf:', b3.result && b3.result.result && b3.result.result.value);
  try { const shot = await send('Page.captureScreenshot', { format: 'png' }); if (shot.result && shot.result.data) { const out = path.join(OUT, 'desk_live.png'); fs.writeFileSync(out, Buffer.from(shot.result.data, 'base64')); console.log('saved', out); } else console.log('shot:', JSON.stringify(shot).slice(0, 200)); } catch (e) { console.log('no screenshot', e.message); }
  ws.close(); process.exit(0);
}); }).on('error', e => { console.log('http error', e.message); process.exit(1); });
setTimeout(() => { console.log('timed out'); process.exit(1); }, 60000);
