'use strict';
const assert = require('node:assert/strict');
const {test} = require('node:test');
const {Mirror} = require('../desktop/tablet-mirror.cjs');
function deferred() {
  let resolve;
  const promise = new Promise(done => { resolve = done; });
  return {promise, resolve};
}
test('parallel opens share a server and a single producer', async () => {
  const mirror = new Mirror();
  let pipes = 0;
  mirror.pipe = () => { pipes++; };
  const answers = await Promise.all([mirror.open(), mirror.open()]);
  assert.equal(answers[0].url, answers[1].url);
  assert.ok(answers[0].port > 0);
  assert.equal(pipes, 1);
  assert.equal(mirror.how().url, answers[0].url);
  mirror.close();
});
test('closing during listen cannot resurrect the producer or leak the server', async () => {
  const mirror = new Mirror();
  let pipes = 0;
  mirror.pipe = () => { pipes++; };
  const opening = mirror.open();
  mirror.close();
  await assert.rejects(opening, /closed while opening/);
  assert.equal(pipes, 0);
  assert.equal(mirror.running, false);
  assert.equal(mirror.server, null);
});
test('opening a paused mirror retains the same local connection URL', async () => {
  const mirror = new Mirror();
  let pipes = 0;
  mirror.pipe = () => { pipes++; };
  mirror.stopRemote = async () => {};
  const first = await mirror.open();
  await mirror.pause();
  assert.equal(mirror.how().paused, true);
  const second = await mirror.open();
  assert.equal(second.url, first.url);
  assert.equal(pipes, 2);
  assert.equal(mirror.how().paused, false);
  mirror.close();
});
test('restoring during slow pause waits for clean shutdown then starts once', async () => {
  const mirror = new Mirror();
  const stop = deferred();
  let pipes = 0;
  mirror.pipe = () => { pipes++; };
  mirror.stopRemote = () => stop.promise;
  await mirror.open();
  const pausing = mirror.pause();
  mirror.resume();
  mirror.resume();
  assert.equal(pipes, 1);
  assert.equal(mirror.running, false);
  stop.resolve();
  await pausing;
  assert.equal(pipes, 2);
  assert.equal(mirror.running, true);
  assert.equal(mirror.how().paused, false);
  mirror.close();
});
test('closing during a slow pause cancels a requested restore', async () => {
  const mirror = new Mirror();
  const stop = deferred();
  let pipes = 0;
  mirror.pipe = () => { pipes++; };
  mirror.stopRemote = () => stop.promise;
  await mirror.open();
  const pausing = mirror.pause();
  mirror.resume();
  const closing = mirror.closeGently();
  stop.resolve();
  await Promise.all([pausing, closing]);
  assert.equal(pipes, 1);
  assert.equal(mirror.running, false);
  assert.equal(mirror.server, null);
  assert.equal((await mirror.open()).ok, false);
});
test('restart waits for the old remote encoder to finish without closing viewers', async () => {
  const mirror = new Mirror();
  const stop = deferred();
  mirror.pipe = () => {};
  mirror.stopRemote = () => stop.promise;
  await mirror.open();
  mirror.frames = 4;
  mirror.pipeFrames = 0;
  let ends = 0;
  mirror.watchers.add({end(){ ends++; }});
  const server = mirror.server;
  mirror.rebuild('transport disappeared');
  assert.equal(mirror.rebuilding, true);
  assert.equal(mirror.retryTimer, null);
  assert.equal(mirror.server, server);
  assert.equal(ends, 0);
  stop.resolve();
  await mirror.stopping;
  await Promise.resolve();
  assert.ok(mirror.retryTimer);
  assert.equal(ends, 0);
  mirror.close();
});
test('a close during pending restart cannot schedule a new encoder', async () => {
  const mirror = new Mirror();
  const stop = deferred();
  mirror.pipe = () => {};
  mirror.stopRemote = () => stop.promise;
  await mirror.open();
  mirror.rebuild('decoder ended');
  mirror.close();
  stop.resolve();
  await mirror.stopping;
  await Promise.resolve();
  assert.equal(mirror.retryTimer, null);
  assert.equal(mirror.running, false);
});

test('a final hide cancels a restore queued during the same slow stop', async () => {
  const mirror = new Mirror();
  const stop = deferred();
  let pipes = 0;
  mirror.pipe = () => { pipes++; };
  mirror.stopRemote = () => stop.promise;
  await mirror.open();
  const pausing = mirror.pause();
  mirror.resume();
  const finalPause = mirror.pause();
  stop.resolve();
  await Promise.all([pausing, finalPause]);
  assert.equal(pipes, 1);
  assert.equal(mirror.running, false);
  assert.equal(mirror.how().paused, true);
  mirror.close();
});
test('pause and restore supersede an older encoder rebuild', async () => {
  const mirror = new Mirror();
  const stop = deferred();
  let pipes = 0;
  mirror.pipe = () => { pipes++; };
  mirror.stopRemote = () => stop.promise;
  await mirror.open();
  mirror.rebuild('network interrupted');
  const pausing = mirror.pause();
  mirror.resume();
  stop.resolve();
  await pausing;
  await Promise.resolve();
  assert.equal(pipes, 2);
  assert.equal(mirror.retryTimer, null);
  assert.equal(mirror.running, true);
  mirror.close();
});
test('a stale quiet-screen probe cannot clear a replacement probe', async () => {
  const mirror = new Mirror();
  const first = deferred();
  const second = deferred();
  mirror.running = true;
  mirror.pipeAt = 1000;
  mirror.frames = 2;
  mirror.pipeFrames = 0;
  mirror.lastFrameAt = 2000;
  mirror.recorderAlive = () => first.promise;
  mirror.health(8000);
  mirror.kill();
  mirror.pipeAt = 1000;
  mirror.frames = 4;
  mirror.pipeFrames = 2;
  mirror.lastFrameAt = 2000;
  mirror.recorderAlive = () => second.promise;
  mirror.health(8000);
  first.resolve(true);
  await Promise.resolve();
  assert.equal(mirror.probing, true);
  assert.equal(mirror.still, false);
  second.resolve(true);
  await Promise.resolve();
  assert.equal(mirror.probing, false);
  assert.equal(mirror.still, true);
  mirror.close();
});


test('balanced capture reduces physical encoder work while preserving full touch dimensions', () => {
  const mirror = new Mirror();
  mirror.real = {width:1340,height:800};
  const balanced = mirror.shapeFor('balanced');
  assert.deepEqual(balanced, {width:960,height:572,bitrate:3020160});
  const full = mirror.shapeFor('full');
  assert.deepEqual(full, {width:1340,height:800,bitrate:5896000});
  assert.ok(balanced.width*balanced.height < full.width*full.height*0.52);
  assert.equal(mirror.where().size,'balanced');
  assert.deepEqual(mirror.where().real, {width:1340,height:800});
  assert.ok(mirror.where().sizes.includes('full'));
});

test('balanced capture follows rotation and does not upscale a smaller tablet', () => {
  const mirror = new Mirror();
  mirror.real = {width:800,height:1340};
  const portrait = mirror.shapeFor('balanced');
  assert.equal(portrait.width,572); assert.equal(portrait.height,960);
  mirror.real = {width:640,height:360};
  const small = mirror.shapeFor('balanced');
  assert.equal(small.width,640); assert.equal(small.height,360);
});
