const {app, BrowserWindow, ipcMain} = require('electron');
const fs = require('node:fs'), path = require('node:path'), os = require('node:os'), assert = require('node:assert/strict');
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'pine-line-tools-qa-'));
app.setPath('userData', temp);
const first = {id: '1234567890abcdef', kind: 'call', who: 'Dill', text: 'Fixture first dialogue'};
const second = {id: 'abcdef1234567890', kind: 'call', who: 'Sam', text: 'Fixture second dialogue'};
const routes = [], cfg = {baseUrl: 'http://127.0.0.1:8096', pip: {}};
let resolveGroups, groupReads = 0;
const flow = {key: '1234567890abcdef', road: 'Fixture conversation', counts: {turns: 1, aired: 1}, nodes: [{id: 'turn-one', type: 'turn', index: 0, who: 'Dill', said: first.text, aired_at: 1, now: true, codes: [first.id]}]};
const groupResult = {at: Date.now()/1000, took_s: .1, tiers: ['cache'], destructive: [], groups: [{id: 'fixture-cache', label: 'Fixture cache', description: 'Fixture data', tier: 'cache', mode: 'hot', reason: 'Test', files: 3, bytes: 2048}], presets: [], kept: [], problems: []};
const deadline = setTimeout(() => app.exit(1), 60000);
app.whenReady().then(async () => {
  ipcMain.handle('agent:get', (_event, route) => {
    routes.push(route);
    if (route.startsWith('/api/filemgr/groups')) {groupReads++;return new Promise(resolve => {resolveGroups = resolve;});}
    if (route === '/api/filemgr/jobs') return {jobs: [], snapshots: []};
    if (route === '/api/flow/now') return {live: true, flow};
    if (route.startsWith('/api/flow/recent')) return {conversations: [{conversation_id: flow.key, topic: 'Fixture conversation'}]};
    if (route.startsWith('/api/flow/')) return flow;
    if (route.startsWith('/api/airlog')) return {events: [first, second]};
    if (route.startsWith('/api/said/repeats')) return {line_id: first.id, text: first.text, played_24h: 1, occurrences_24h: 2, writing_iterations: 0, causes: [], current_inputs: [], history: [], coverage: 'Fixture coverage', writing: [], iterations: [], carriers: [], rounds: []};
    if (route.startsWith('/api/said/why/')) return {id: first.id, text: first.text};
    return {ok: true, items: [], rows: [], events: [], roads: [], settings: {}, store: {}};
  });
  ipcMain.handle('agent:post', (_event, route) => {throw Error('Opening a tool must not mutate the station: ' + route);});
  const manager = require('../desktop/pip-tools-window.cjs').install({BrowserWindow, ipcMain, getWindow: () => null,
    rendererDir: path.resolve(__dirname, '../desktop/renderer'), preload: path.resolve(__dirname, '../desktop/preload.js'),
    readConfig: () => cfg, writeConfig: value => Object.assign(cfg, value)});
  manager.open();const win = manager.getWindow(), errors = [];
  win.webContents.on('console-message', (_event, level, message) => {if(level>=2&&!message.includes('Electron Security Warning'))errors.push(message);});
  await new Promise(resolve => win.webContents.once('did-finish-load', resolve));
  const evaluate = code => win.webContents.executeJavaScript(code);
  await evaluate('pineToolsReady');await wait(100);
  win.webContents.send('pip:tools-feed', {station: {}, rows: [first, second]});await wait(50);
  const choose = id => evaluate('PinePipPopups.select(' + JSON.stringify('module:' + id) + ')');
  const noStation = async () => {
    assert.equal(await evaluate("document.querySelectorAll('webview').length"),0);
    assert.equal(await evaluate('typeof PineScriptPage'),'undefined');
    assert.equal(await evaluate('typeof PineSfxTv'),'undefined');
  };
  const start = Date.now();await choose('PineFileMgr');
  assert.ok(Date.now()-start<1500,'File Manager opens without waiting for its disk scan');
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.fm-pop')).display"),'flex');
  assert.match(await evaluate("document.querySelector('.fm-list').textContent"),/Measuring/);
  await evaluate('PinePipPopups.clear()');await choose('PineFileMgr');await wait(100);
  assert.equal(groupReads,1,'Reopening coalesces the pending disk scan');
  resolveGroups(groupResult);await wait(100);
  assert.match(await evaluate("document.querySelector('.fm-list').textContent"),/Fixture cache/);
  await noStation();
  await choose('PineFlowChart');await wait(200);
  assert.equal(await evaluate("!!document.querySelector('#pinePipFlowChart.pip-popup-visible')"),true);
  assert.match(await evaluate("document.querySelector('.fc-status').textContent"),/Fixture conversation/);
  assert.match(await evaluate("document.querySelector('.fc-body').textContent"),/Fixture first dialogue/);
  await evaluate('PinePipPopups.clear()');
  const flowReads = routes.filter(route=>route==='/api/flow/now').length;
  await wait(2200);assert.equal(routes.filter(route=>route==='/api/flow/now').length,flowReads,'Hidden native chart stops polling');
  await choose('PineFlowChart');
  await choose('PineLineActions');assert.equal(await evaluate('PinePipPopups.state().current'),'module:PineLineActions','Switching directly from the chart does not cancel the next tool');await wait(100);
  assert.match(await evaluate("document.querySelector('.la-said').textContent"),/second dialogue/);
  assert.equal(await evaluate("document.querySelector('.pip-line-context select').options.length"),3);
  await evaluate("const p=document.querySelector('.pip-line-context select');p.value='1234567890abcdef';p.dispatchEvent(new Event('change',{bubbles:true}))");
  await wait(100);assert.match(await evaluate("document.querySelector('.la-said').textContent"),/first dialogue/);
  await evaluate("window.__storyImports=[];window.__storyDisposed=0;window.pineToolsImport=route=>{__storyImports.push(route);return Promise.resolve({mountLineStory:host=>{host.textContent='Fixture System 3 story';return Promise.resolve({dispose(){window.__storyDisposed++}})}})};true");
  await choose('PineLineDeep');await wait(200);
  assert.match(await evaluate("document.querySelector('.ld-said').textContent"),/first dialogue/);
  assert.ok(routes.some(route=>route.includes('/api/dj/provenance/'+first.id)));
  assert.deepEqual(await evaluate('window.__storyImports'),['/system3/system3.js?v=8'],'Line provenance uses the independent station module loader');
  assert.match(await evaluate("document.querySelector('.ld-body').textContent"),/Fixture System 3 story/);
  await choose('PineLineRepeat');await wait(200);assert.equal(await evaluate('window.__storyDisposed'),1,'Closing provenance releases its System 3 story');
  assert.match(await evaluate("document.querySelector('.lr-body').textContent"),/Fixture first dialogue/);
  assert.ok(routes.some(route=>route.startsWith('/api/said/repeats?line_id='+first.id)));
  await noStation();
  await evaluate('PinePipPopups.clear()');win.webContents.send('pip:tools-feed',{station:{},rows:[]});await wait(50);
  await choose('PineLineRepeat');
  assert.match(await evaluate("document.getElementById('pinePipLineEmpty').textContent"),/No recent dialogue/);
  await evaluate("[...document.querySelectorAll('.pip-line-context button')].find(b=>b.textContent==='Refresh lines').click()");
  await wait(100);assert.ok(await evaluate("!!document.querySelector('.lr-sheet .pip-line-context')"),'Empty line picker can load station history');
  assert.ok(errors.every(e=>/THREE|WebGL|Three|404|line-story/.test(e)),JSON.stringify(errors));
  console.log('Native line tools: pending file scan, cache reuse, live chart and cleanup, line search/selection, actions, provenance, repeats and empty history passed');
  win.destroy();clearTimeout(deadline);app.exit(0);
}).catch(error=>{console.error(error);clearTimeout(deadline);app.exit(1);});
