const {app,BrowserWindow,ipcMain}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url');const http=require('node:http');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pine-generated-media-qa-'));app.setPath('userData',temp);
const timeout=setTimeout(()=>app.exit(1),60000),delay=ms=>new Promise(r=>setTimeout(r,ms));
const onePixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aP1sAAAAASUVORK5CYII=','base64');
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','image/png');res.end(onePixel);});
app.whenReady().then(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 const root=path.resolve(__dirname,'..'),local=path.join(temp,'renderer');fs.mkdirSync(local);
 for(const name of ['styles.css','pine-pip.css','three-full.css','pine-icons.js','pine-stick.js','pine-vitals.js','pine-dismiss.js','pine-closex.js','three-full.js','pip-tools-bootstrap.js','pine-pip-popups.js','generated-media.js','generated-media.css','pineicons.css'])fs.copyFileSync(path.join(root,'desktop/renderer',name),path.join(local,name));
 fs.writeFileSync(path.join(local,'index.html'),'<script src="generated-media.js"></script><link rel="stylesheet" href="generated-media.css">');fs.writeFileSync(path.join(local,'renderer.js'),'const THREEJS_VIEWS = [];');
 fs.writeFileSync(path.join(local,'audio-mixer.html'),'<html></html>');fs.writeFileSync(path.join(local,'station-troubleshooter.html'),'<html></html>');
 const preload=path.join(temp,'preload.js');fs.copyFileSync(path.join(root,'desktop/preload.js'),preload);
 const calls=[],errors=[];let events=0;const item={id:'one',prompt_id:'p-one',file:'one.png',kind:'image',title:'A real Comfy image',tags:'Original direction',url:base+'/one.png',poster:base+'/one.png'};
 ipcMain.handle('agent:get',(_e,route)=>{calls.push({method:'get',route});if(route.startsWith('/api/generated-media/events'))return {events:events++?[item]:[],cursor:'epoch:1'};if(route==='/api/generated-media/item/one')return item;if(route.startsWith('/api/generations/history'))return {generations:[{prompt_id:'previous',kind:'video',tags:'An earlier real prompt',request:'Earlier render'}],next:''};if(route==='/api/h3/prompts')return {presets:[{id:'saved',name:'Saved H3 look',goal:'a rotary phone',clip:'Sell {goal}',constraints:'No overlays'}]};return {};});
 ipcMain.handle('agent:post',(_e,route,payload)=>{calls.push({method:'post',route,payload});return {prompt_id:'new',analysis:'Actual image analysis'};});
 const main=new BrowserWindow({show:false,width:440,height:340,webPreferences:{preload,offscreen:true,sandbox:false,contextIsolation:true}});await main.loadURL('data:text/html,<html><body></body></html>');
 class HiddenToolWindow extends BrowserWindow{constructor(opts){super({...opts,show:false,webPreferences:{...opts.webPreferences,offscreen:true}});}show(){this.__showRequested=true;}focus(){}}
 const manager=require('../desktop/pip-tools-window.cjs').install({app,BrowserWindow:HiddenToolWindow,ipcMain,getWindow:()=>main,rendererDir:local,preload,readConfig:()=>({baseUrl:base,pip:{}}),writeConfig:()=>{}});
 // A visible DOM tile must live in the outer PiP renderer, even though the broadcast pane is hidden.
 const file=path.join(temp,'main.html');fs.writeFileSync(file,`<html><head><link rel="stylesheet" href="${pathToFileURL(path.join(local,'pine-pip.css')).href}"><link rel="stylesheet" href="${pathToFileURL(path.join(local,'generated-media.css')).href}"></head><body class="pine-pip"><main hidden></main><script>window.PinePip={state:()=>({active:true})};window.desktopMusicUrl=p=>p;</script><script src="${pathToFileURL(path.join(local,'generated-media.js')).href}"></script></body></html>`);await main.loadFile(file);await main.webContents.executeJavaScript('PineGeneratedMedia.poll()');await delay(1500);
 const tile=await main.webContents.executeJavaScript(`(()=>{const t=document.querySelector('.gm-polaroid');const r=t.getBoundingClientRect();return {phase:t.dataset.phase,display:getComputedStyle(t).display,dock:getComputedStyle(t.parentElement).display,pointer:getComputedStyle(t).pointerEvents,width:r.width,loaded:t.querySelector('img').naturalWidth>0}})()`);
 assert.equal(tile.phase,'hold');assert.equal(tile.dock,'block');assert.equal(tile.pointer,'auto');assert.ok(tile.width>0);assert.equal(tile.loaded,true);
 await main.webContents.executeJavaScript('document.querySelector(".gm-polaroid").click()');
 for(let i=0;i<80;i++){const tools=manager.getWindow();if(tools&&await tools.webContents.executeJavaScript('!!document.querySelector(".gm-review")').catch(()=>false))break;await delay(100);}
 const tools=manager.getWindow();assert.ok(tools);assert.equal(tools.isDestroyed(),false);assert.equal(main.isVisible(),false,'popup does not depend on showing the hidden broadcast main');
 tools.webContents.on('console-message',(_e,level,message)=>{if(level>=2)errors.push(message);});
 await delay(150);assert.equal(await tools.webContents.executeJavaScript('typeof PineGeneratedMediaReview'),'object');
 const panel=await tools.webContents.executeJavaScript(`({display:getComputedStyle(document.querySelector('.gm-review-shade')).display,image:document.querySelector('.gm-review-media').naturalWidth>0,prompt:document.querySelector('.gm-review-prompt').value,history:[...document.querySelector('.gm-review-history select').options].map(o=>o.textContent),title:document.title})`);
 assert.equal(panel.display,'grid');assert.equal(panel.image,true);assert.equal(panel.prompt,'Original direction');assert.ok(panel.history.some(t=>t.includes('Saved H3 look')));assert.ok(panel.history.some(t=>t.includes('Earlier render')));
 await tools.webContents.executeJavaScript(`document.querySelector('.gm-review-history select').value='generation:previous';[...document.querySelectorAll('button')].find(b=>b.textContent==='Assign prompt').click()`);await delay(30);assert.equal(await tools.webContents.executeJavaScript('document.querySelector(".gm-review-prompt").value'),'An earlier real prompt');
 await tools.webContents.executeJavaScript(`[...document.querySelectorAll('button')].find(b=>b.textContent==='Regenerate video (H3)').click()`);await delay(50);const h3=calls.find(c=>c.route==='/api/comfy/workshop');assert.equal(h3.payload.source,'one.png');assert.equal(h3.payload.mode,'frame');assert.equal(h3.payload.prompt,'An earlier real prompt');assert.equal(h3.payload.air_it,false);
 await tools.webContents.executeJavaScript(`[...document.querySelectorAll('button')].find(b=>b.textContent==='Regenerate image').click()`);await delay(50);assert.equal(calls.find(c=>c.route==='/api/generate').payload.prompt,'An earlier real prompt');
 await tools.webContents.executeJavaScript(`[...document.querySelectorAll('button')].find(b=>b.textContent==='Analyze').click()`);await delay(50);assert.equal(await tools.webContents.executeJavaScript('document.querySelector(".gm-review-analysis").textContent'),'Actual image analysis');
 fs.writeFileSync(path.join(root,'work/generated-media-review-fixture.png'),(await tools.webContents.capturePage()).toPNG());
 await tools.webContents.executeJavaScript('PineGeneratedMediaReview.close()');assert.equal(await tools.webContents.executeJavaScript('document.querySelectorAll(".gm-review-shade").length'),0);
 assert.equal(calls.filter(c=>c.method==='post').length,3,'no generation or playback is triggered by showing or clicking notices');assert.ok(errors.every(e=>e.includes('Electron Security Warning')),JSON.stringify(errors));
 fs.writeFileSync(path.join(root,'work/generated-media-browser-proof.json'),JSON.stringify({tile,panel,posted:calls.filter(c=>c.method==='post'),nativeWindowIndependent:true,errors},null,2));
 console.log('Generated media browser QA passed: real PiP thumbnail, still 3s, clickable native window with main hidden, prior prompts and saved presets, correct image/H3/analysis actions, cleanup.');manager.getWindow().destroy();main.destroy();server.close();clearTimeout(timeout);app.exit(0);
}).catch(e=>{console.error(e);clearTimeout(timeout);app.exit(1)});
