const {app,BrowserWindow,ipcMain}=require('electron');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pine-orchestra-tools-qa-'));app.setPath('userData',temp);
let replies=[],glassReads=0;const gets=[];
const payload={at:Date.now()/1000,on:true,paused:false,face:{mood:'thinking',say:'Fixture conductor is working'},coverage:{stamped_loops:1,total_loops:1},live:[],recent:[],keepers:[],roads:[],commission:{},rooms:[],asks:[],commands:[]};
const timeout=setTimeout(()=>app.exit(1),60000);
app.whenReady().then(async()=>{
 ipcMain.handle('agent:get',(_e,route)=>{gets.push(route);if(route==='/api/orchestrator/glass'){glassReads++;return new Promise((resolve,reject)=>replies.push({resolve,reject}));}return {live:false,ok:true,rows:[],items:[],events:[]};});
 ipcMain.handle('agent:post',()=>{throw Error('Opening orchestra controls must not change the station');});
 const manager=require('../desktop/pip-tools-window.cjs').install({BrowserWindow,ipcMain,getWindow:()=>null,rendererDir:path.resolve(__dirname,'../desktop/renderer'),preload:path.resolve(__dirname,'../desktop/preload.js'),readConfig:()=>({baseUrl:'http://127.0.0.1:8096',pip:{}}),writeConfig:()=>{}});
 manager.open();const win=manager.getWindow();await new Promise(r=>win.webContents.once('did-finish-load',r));const js=s=>win.webContents.executeJavaScript(s);await js('pineToolsReady');await wait(100);
 await js("localStorage.setItem('pineOrchGlassMin','1');true");
 const start=Date.now();await js("PinePipPopups.select('module:PineOrchGlass')");assert.ok(Date.now()-start<1500);
 assert.equal(await js('PineOrchGlass.isFolded()'),false,'Native controls open expanded despite the saved desktop pill');
 assert.equal(await js("document.querySelector('.og-main').hidden"),false);
 assert.equal(await js("getComputedStyle(document.getElementById('pineOrchGlass')).display"),'flex');
 assert.ok(await js("document.querySelector('.og-head .pi-icon').getBoundingClientRect().width<24"),'Shared icon sizing is present in the independent shell');
 assert.ok(await js("document.querySelector('.og-main').getBoundingClientRect().height>=90"),'The scrolling control list retains usable space');
 assert.ok(await js("document.querySelector('.og-cmd').getBoundingClientRect().bottom<=document.getElementById('pineOrchGlass').getBoundingClientRect().bottom"),'Command controls remain inside the pane');
 assert.match(await js("document.querySelector('.og-main').textContent"),/Loading station measurements/);
 assert.equal(await js('typeof PineScriptPage'),'undefined');assert.equal(await js('typeof PineSampler'),'undefined');assert.equal(await js('typeof PineSfxTv'),'undefined');
 assert.equal(await js("!!document.getElementById('pineOrchDot')"),false,'Native popup does not plant an extra persistent launcher');
 await js("document.getElementById('pineOrchGlass').dispatchEvent(new Event('pointerenter'));true");
 await wait(5250);assert.equal(glassReads,1,'Slow station scans do not accumulate concurrent requests');
 replies[0].resolve(payload);await wait(250);
 assert.ok(await js("document.querySelector('.og-main').children.length>5"),'First snapshot renders even while the pointer is inside');
 assert.match(await js("document.getElementById('pineOrchGlass').textContent"),/Fixture conductor/);
 await js("PineOrchGlass.close();true");
 await js("PinePipPopups.clear().then(()=>PinePipPopups.select('module:PineOrchGlass'))");
 assert.ok(await js("document.querySelector('.og-main').children.length>5"),'Reopening paints the cached snapshot immediately');
 const old=replies[1];await js('PinePipPopups.clear()');
 await js("PinePipPopups.select('module:PineOrchGlass')");
 old.resolve({...payload,face:{mood:'thinking',say:'STALE closed window'}});await wait(100);
 assert.doesNotMatch(await js("document.querySelector('.og-say-text').textContent"),/STALE/);
 replies[2].reject(Error('Fixture station unavailable'));for(let attempt=0;attempt<60;attempt++){if(await js("!!document.querySelector('.og-retry')"))break;await wait(50);}
 assert.ok(await js("!!document.querySelector('.og-retry')"),'Read failure offers retry');
 await js("document.querySelector('.og-retry').click();true");await wait(100);assert.equal(glassReads,4);
 replies[3].resolve({...payload,face:{mood:'thinking',say:'Fixture retry succeeded'}});await wait(100);
 assert.match(await js("document.querySelector('.og-say-text').textContent"),/retry succeeded/);
 await js('PinePipPopups.clear()');const count=gets.length;await wait(5300);assert.equal(gets.length,count,'Closed native orchestra controls stop polling');
 assert.equal(await js("document.querySelectorAll('webview').length"),0);
 console.log('Native orchestra controls passed: independent loading, expanded state, initial hover render, coalesced slow reads, cache, stale-response protection, retry and polling cleanup');
 win.destroy();clearTimeout(timeout);app.exit(0);
}).catch(e=>{console.error(e);clearTimeout(timeout);app.exit(1)});
