'use strict';
const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'pine-sidebar-test-'));app.setPath('userData',temp);app.disableHardwareAcceleration();
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const deadline=setTimeout(()=>{console.error('Sidebar test timed out');app.exit(1);},45000);
app.whenReady().then(async()=>{
 const root=path.resolve(__dirname,'..'),file=path.join(temp,'index.html');
 const asset=name=>pathToFileURL(path.join(root,'desktop/renderer',name)).href;
 fs.writeFileSync(file,'<!doctype html><html><head><link rel="stylesheet" href="'+asset('styles.css')+'"><link rel="stylesheet" href="'+asset('pine-pip.css')+'"></head><body class="pine-pip pine-native-tools"><main><section id="control" class="view"></section><section id="script" class="view" hidden>Script view</section></main><script>'+String.raw`
 window.PINE_NATIVE_TOOLS=true;
 window.pineDesktop={pipUpdate:async value=>value};
 window.PinePopupScenes=Array.from({length:40},(_,i)=>({key:'fixture'+i,name:'Fixture '+i})).concat({key:'failure',name:'Fixture failure'});
 window.PinePopBack={isPopup:el=>el.id==='fixtureScene'};
 window.pineToolsSceneRoots=()=>[document.getElementById('fixtureScene')].filter(Boolean);
 window.pineToolsSceneClose=()=>document.getElementById('fixtureScene')?.remove();
 window.pineToolsSceneOpen=async key=>{
  if(key==='failure')throw Error('Fixture opening failure');
  const panel=document.createElement('aside');panel.id='fixtureScene';panel.innerHTML='<input aria-label="Tool setting" value="content">';document.body.appendChild(panel);panel.querySelector('input').focus();
  if(key==='fixture30')await new Promise(resolve=>{window.finishPending=resolve});
 };
 window.PineViewRail={open:async id=>{document.getElementById('script').hidden=id!=='script';},close:()=>{document.getElementById('script').hidden=true;}};
 `+'</script><script src="'+asset('pine-pip-popups.js')+'"></script></body></html>');
 const win=new BrowserWindow({show:false,width:1000,height:620,webPreferences:{offscreen:true,sandbox:false,backgroundThrottling:false}});
 await win.loadFile(file);const evaluate=code=>win.webContents.executeJavaScript(code);
 await evaluate('PinePipPopups.sync({active:true,popupFavorites:[]});PinePipPopups.open()');
 const click=async selector=>{
  const point=await evaluate('(()=>{const r=document.querySelector('+JSON.stringify(selector)+').getBoundingClientRect();return {x:Math.round(r.left+r.width/2),y:Math.round(r.top+r.height/2)}})()');
  win.webContents.sendInputEvent({type:'mouseMove',...point});win.webContents.sendInputEvent({type:'mouseDown',button:'left',clickCount:1,...point});win.webContents.sendInputEvent({type:'mouseUp',button:'left',clickCount:1,...point});await wait(100);
 };
 const snapshot=()=>evaluate("({selected:PinePipPopups.state().selected,highlight:document.querySelector('.pip-popup-list .selected')?.dataset.popup,focus:document.activeElement?.dataset.popup,scroll:document.querySelector('.pip-popup-list').scrollTop,search:document.querySelector('.pip-popup-dock input').value})");
 await evaluate("window.targetRow=document.querySelector('.pip-popup-list [data-popup=\"scene:fixture28\"]');targetRow.scrollIntoView({block:'center'});window.initialScroll=document.querySelector('.pip-popup-list').scrollTop;");
 await click('.pip-popup-list [data-popup="scene:fixture28"]');
 let state=await snapshot();assert.equal(state.selected,'scene:fixture28');assert.equal(state.highlight,state.selected);assert.equal(state.focus,state.selected);assert(state.scroll>100);
 assert.equal(state.scroll,await evaluate('initialScroll'),'selecting a visible item does not reset or move the sidebar');
 const firstScroll=state.scroll;
 await evaluate("PinePipPopups.sync({active:true,popupFavorites:['scene:fixture28']});PinePipPopups.open()");
 state=await snapshot();assert.equal(state.scroll,firstScroll);assert.equal(state.focus,'scene:fixture28');
 assert.equal(await evaluate("document.querySelector('.pip-popup-list [data-popup=\"scene:fixture28\"]')===targetRow"),true,'catalog and preference updates retain the same sidebar button');
 assert.match(await evaluate('targetRow.textContent'),/^\u2605 Fixture 28/);
 await evaluate("PineViewRail.open('script');PinePipPopups.sync({active:true,popupFavorites:['scene:fixture28']})");
 state=await snapshot();assert.equal(state.selected,'scene:fixture28');assert.equal(state.focus,state.selected);assert.equal(state.scroll,firstScroll,'changing the content view preserves sidebar navigation');
 await click('.pip-popup-list [data-popup="scene:fixture29"]');
 state=await snapshot();assert.equal(state.highlight,'scene:fixture29');assert.equal(state.focus,state.highlight);assert.equal(state.scroll,firstScroll);
 assert.equal(await evaluate('targetRow.isConnected'),true,'switching tools keeps existing buttons mounted');
 // A tool completing later must not take focus back after the user starts searching.
 await evaluate("document.querySelector('.pip-popup-list [data-popup=\"scene:fixture30\"]').scrollIntoView({block:'nearest'});window.pendingSelect=PinePipPopups.select('scene:fixture30');true");await wait(80);
 assert.equal((await snapshot()).highlight,'scene:fixture30','selection is shown immediately while loading');
 await click('.pip-popup-dock input');win.webContents.insertText('Fixture');await wait(60);
 await evaluate('finishPending();pendingSelect');
 assert.equal(await evaluate("document.activeElement===document.querySelector('.pip-popup-dock input')"),true,'user focus during loading is preserved');
 assert.equal((await snapshot()).search,'Fixture');
 const filteredScroll=(await snapshot()).scroll;
 await evaluate("PinePipPopups.sync({active:true,popupFavorites:[]});PinePipPopups.open()");
 assert.equal((await snapshot()).scroll,await evaluate('Math.min('+filteredScroll+',document.querySelector(".pip-popup-list").scrollHeight-document.querySelector(".pip-popup-list").clientHeight)'),'removing the favorites row only clamps at the new scroll limit');assert.equal((await snapshot()).search,'Fixture');
 assert.equal(await evaluate("document.activeElement===document.querySelector('.pip-popup-dock input')"),true,'a repeated open does not move focus to another control');
 await evaluate("const input=document.querySelector('.pip-popup-dock input');input.value='';input.dispatchEvent(new Event('input'));PinePipPopups.select('scene:failure')");
 state=await snapshot();assert.equal(state.highlight,'scene:failure');assert.equal(state.focus,'scene:failure','a failed tool remains selected and focused');
 const failedScroll=state.scroll;
 await evaluate('PinePipPopups.clear();PinePipPopups.sync({active:true,popupFavorites:[]})');
 state=await snapshot();assert.equal(state.highlight,'scene:failure');assert.equal(state.scroll,failedScroll,'closing content does not clear the sidebar selection');
 await evaluate('(async()=>{await PinePipPopups.close();PinePipPopups.open();})()');
 state=await snapshot();assert.equal(state.highlight,'scene:failure');assert.equal(state.focus,'scene:failure');assert.equal(state.scroll,failedScroll);
 // Favorites wrap with the window; tools begin below every tab row.
 await evaluate("PinePipPopups.sync({active:true,popupFavorites:Array.from({length:17},(_,i)=>'scene:fixture'+i)})");await wait(100);
 const layout=()=>evaluate("(()=>{const b=document.getElementById('pinePipFavorites'),r=b.getBoundingClientRect(),tabs=[...b.children].map(n=>({text:n.textContent,...(()=>{const q=n.getBoundingClientRect();return {left:q.left,right:q.right,top:q.top,bottom:q.bottom}})()})),dock=document.getElementById('pinePipPopupDock').getBoundingClientRect();return {width:innerWidth,height:r.height,bottom:r.bottom,scroll:b.scrollWidth,client:b.clientWidth,overflow:getComputedStyle(b).overflowX,rows:new Set(tabs.map(n=>n.top)).size,tabs,dock:dock.top}})()");
 let wide=await layout();assert(wide.rows>1);assert(wide.tabs.every(tab=>!tab.text.startsWith('\u2605')));assert(wide.scroll<=wide.client+1);assert.equal(wide.overflow,'hidden');assert(wide.dock>=wide.bottom,'sidebar stays below wrapped favorites');
 win.setSize(480,620);await wait(180);let narrow=await layout();assert(narrow.rows>wide.rows,'narrower windows add tab rows');assert(narrow.scroll<=narrow.client+1);assert(narrow.tabs.every(tab=>tab.left>=0&&tab.right<=narrow.width+1));assert(narrow.dock>=narrow.bottom);
 await evaluate("PinePipPopups.select('view:script')");await wait(100);
 assert.equal(await evaluate("(()=>{const b=document.getElementById('pinePipFavorites').getBoundingClientRect(),p=document.getElementById('script').getBoundingClientRect();return p.top>=b.bottom&&p.bottom<=innerHeight})()"),true,'the open view clears all favorite rows');
 win.setSize(1200,620);await wait(180);const expanded=await layout();assert(expanded.rows<narrow.rows);assert(expanded.dock>=expanded.bottom);
 await evaluate("document.body.classList.remove('pine-native-tools');window.PINE_NATIVE_TOOLS=false;PinePipPopups.sync({active:true,popupFavorites:['scene:fixture1']})");
 assert.equal(await evaluate("getComputedStyle(document.getElementById('pinePipFavorites')).display"),'none','broadcast PiP never displays tabs');
 assert.equal(await evaluate("document.getElementById('pinePipFavorites').hidden"),true);
 await evaluate("document.body.classList.add('pine-native-tools');window.PINE_NATIVE_TOOLS=true;PinePipPopups.sync({active:true,popupFavorites:Array.from({length:17},(_,i)=>'scene:fixture'+i)})");await wait(100);
 fs.writeFileSync(path.join(root,'work/pip-sidebar-fixture.png'),(await win.webContents.capturePage()).toPNG());
 console.log('Pine sidebar: real clicks preserve selection, scroll and focus; stable DOM survives updates/views; loading respects user focus; filtering, failures and reopen preserve navigation.');
 win.destroy();clearTimeout(deadline);app.exit(0);
}).catch(error=>{console.error(error);clearTimeout(deadline);app.exit(1);});
