const {app,BrowserWindow}=require('electron'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{pathToFileURL}=require('node:url');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'pine-rhetoric-'));app.setPath('userData',dir);const wait=ms=>new Promise(r=>setTimeout(r,ms));const deadline=setTimeout(()=>app.exit(1),50000);
app.whenReady().then(async()=>{
 const uri=n=>pathToFileURL(path.resolve(__dirname,'../desktop/renderer/'+n)).href,three=pathToFileURL(path.resolve(__dirname,'../desktop/vendor/three.module.js')).href;
 const words=Array.from({length:350},(_,i)=>'voice'+String.fromCharCode(97+Math.floor(i/26),97+i%26)).join(' ');
 const file=path.join(dir,'index.html');fs.writeFileSync(file,`<html><head><link rel="stylesheet" href="${uri('pine-pip.css')}"></head><body class="pine-pip pine-native-tools pip-popups-open"><script>window.pineToolsImport=()=>import(${JSON.stringify(three)});window.djLastState={chat:[{who:'dj',text:${JSON.stringify(words)}},{who:'operator',text:'excludedword'}]};</script><script src="${uri('rhetoric-sphere.js')}"></script></body></html>`);
 const win=new BrowserWindow({show:false,width:1000,height:700,webPreferences:{offscreen:true,sandbox:false}});await win.loadFile(file);
 const open=()=>win.webContents.executeJavaScript("(async()=>{window.scene=await PineRhetoricSphere.open();scene.element.classList.add('pip-popup-visible');return true})()");await open();await wait(600);
 const measure=()=>win.webContents.executeJavaScript("(()=>{const h=scene.element.querySelector('.pine-win-host'),c=h.querySelector('canvas'),b=h.getBoundingClientRect();return {height:b.height,width:b.width,bottom:b.bottom,viewport:innerHeight,canvasHeight:c.height,canvasWidth:c.width,state:scene.state(),status:scene.element.querySelector('[role=status]').textContent}})()");
 let m=await measure();assert(m.height>500,'sphere fills the tools body');assert(Math.abs(m.bottom-m.viewport)<8);assert(m.canvasHeight>=m.height);assert.equal(m.state.shown,90);assert.equal(m.state.available,350,'operator words excluded');
 const set=async n=>{await win.webContents.executeJavaScript(`(()=>{const s=document.querySelector('[type=range]');s.value='${n}';s.dispatchEvent(new Event('input'));return true})()`);};
 await set(200);assert.equal((await measure()).state.shown,200,'slider increases words immediately');await set(500);assert.equal((await measure()).state.shown,350,'limit uses only available words');await set(20);assert.equal((await measure()).state.shown,20,'slider decreases words immediately');await set(200);
 const shot=(await win.webContents.capturePage()).toPNG();await wait(800);assert(!shot.equals((await win.webContents.capturePage()).toPNG()),'sphere remains animated');
 win.setSize(480,800);await wait(400);m=await measure();assert(m.height>600);assert(Math.abs(m.bottom-m.viewport)<8);assert(m.canvasHeight>=m.height);assert(m.canvasWidth>=m.width);
 await win.webContents.executeJavaScript("djLastState.chat=[{who:'caller',text:'broadcast orchard harbour garden'}];true");await wait(4200);assert.equal((await measure()).state.shown,4,'live dialogue continues updating');
 await win.webContents.executeJavaScript('scene.close();true');assert.equal(await win.webContents.executeJavaScript("!!document.getElementById('pineWin-sphere')"),false);await open();assert.equal((await measure()).state.limit,200,'word limit survives closing and reopening');await win.webContents.executeJavaScript('scene.close();true');
 console.log('Rhetoric Sphere passed: full-area canvas, resizing, immediate 20-500 word slider, speaker filtering, live updates, persistent setting, continuous animation and cleanup.');win.destroy();clearTimeout(deadline);app.exit(0);
}).catch(e=>{console.error(e);clearTimeout(deadline);app.exit(1)});
