#!/usr/bin/env python3
"""closex_panel_legacy - the station panel's hand-rolled X's handed to
pineCloseX. Each popup below already had a close glyph (a span or button
holding a cross) - but placed by its header row, so it sat mid-bar (the
hangup rules: half-way along), clipped (the booth), unlabelled, 18 px, and
deaf to Escape. One line per builder, right after the old X is attached:

    if (window.pineCloseX) { window.pineCloseX(POPUP, () => OLD.click()); OLD.remove(); }

The corner X calls the OLD X's own handler, so the road out is unchanged:
whatever that X tore down, stopped or put back, it still does. Generated by
gen_legacy.js from the builders' own code; every row is scoped to its
builder's signature.

    python closex_panel_legacy.py --check <repo-root>
    python closex_panel_legacy.py --apply <repo-root>
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from closex_patchlib import Insert, main  # noqa: E402

SKIP = {
    # the old X called toggleCloud(), which RE-OPENS when the cloud never
    # mounted - closex_panel.py gives this one its own close road instead
    "cloudPopupOpen",
}


def L(fname, sig, anchor, popup, x, ind, within):
    marker = f"closex:legacy:{fname}:{x}"
    return Insert("app.py", marker, anchor,
                  f"{ind}if (window.pineCloseX) {{ window.pineCloseX({popup}, () => {x}.click()); {x}.remove(); }}  // [{marker}]",
                  where="after", scope=sig, within=within)


ROWS = [
    L("pineWin", "function pineWin(key, title, opts) {", "  head.appendChild(shut);", "box", "shut", "  ", 25),
    L("pineSlidesBuild", "function pineSlidesBuild() {", "  pane.appendChild(shut);", "pane", "shut", "  ", 20),
    L("gazHourOpen", "async function gazHourOpen(hour) {", "  head.appendChild(x);", "shade", "x", "  ", 30),
    L("cloudPopupOpen", "function cloudPopupOpen() {", "  head.appendChild(x);", "box", "x", "  ", 23),
    L("albumFocus", "async function albumFocus(host, album) {", "  head.appendChild(shut);", "list", "shut", "  ", 27),
    L("djTalkPopup", "function djTalkPopup() {", "  head.appendChild(shut);", "box", "shut", "  ", 211),
    L("callerDossier", "async function callerDossier(name, tab) {", "  head.appendChild(x);", "box", "x", "  ", 25),
    L("hangupRules", "async function hangupRules(focusId) {", "  head.appendChild(x);", "box", "x", "  ", 21),
    L("callerCases", "async function callerCases(focusId) {", "  head.appendChild(x);", "box", "x", "  ", 21),
    L("adArchivePopup", "async function adArchivePopup(focusId) {", "  head.appendChild(x);", "box", "x", "  ", 22),
    L("djDossierShow", "function djDossierShow(line, anchorEl) {", "  head.appendChild(x);", "card", "x", "  ", 33),
    L("djProvenanceShow", "async function djProvenanceShow(line, event) {", "  head.appendChild(shut);", "pop", "shut", "  ", 27),
    L("pineSheet", "async function pineSheet(line) {", "  head.appendChild(shut);", "sheet", "shut", "  ", 32),
    L("pineMediaSettings", "function pineMediaSettings() {", "  bar.appendChild(x);", "box", "x", "  ", 20),
    L("sfxInspect", "async function sfxInspect(sfxId) {", "  head.appendChild(shut);", "card", "shut", "  ", 26),
    L("artHawkPanel", "async function artHawkPanel(names) {", "  head.appendChild(x);", "box", "x", "  ", 22),
    L("sparkQueuePopup", "async function sparkQueuePopup(event) {", "  head.appendChild(x);", "box", "x", "  ", 23),
    L("pineboxStatus", "async function pineboxStatus() {", "  head.appendChild(x);", "box", "x", "  ", 22),
    L("pineboxInitialize", "async function pineboxInitialize() {", "  head.appendChild(x);", "box", "x", "  ", 22),
    L("docLockPanel", "async function docLockPanel() {", "  head.appendChild(shut);", "card", "shut", "  ", 24),
    L("remotePanel", "async function remotePanel() {", "  head.appendChild(shut);", "card", "shut", "  ", 21),
    L("artistReadPanel", "async function artistReadPanel() {", "  head.appendChild(shut);", "card", "shut", "  ", 21),
    L("djRepairPopup", "function djRepairPopup() {", "  head.appendChild(shut);", "card", "shut", "  ", 39),
    L("djRepairPopup", "function djRepairPopup() {", "          pop.appendChild(x);", "pop", "x", "          ", 162),
    L("phoneRingStudio", "async function phoneRingStudio() {", "  head.appendChild(x);", "box", "x", "  ", 22),
    L("deskPanel", "function deskPanel(anchor) {", "  hd.appendChild(shut);", "pop", "shut", "  ", 35),
    L("djConverseHistory", "async function djConverseHistory() {", "  head.appendChild(shut);", "pop", "shut", "  ", 19),
    L("djPromptManage", "function djPromptManage() {", "  head.appendChild(x);", "card", "x", "  ", 20),
    L("cacheTranscript", "async function cacheTranscript(base, r) {", "  head.appendChild(x);", "box", "x", "  ", 31),
    L("stagingDesk", "async function stagingDesk() {", "  head.appendChild(x);", "box", "x", "  ", 25),
    L("callRecordings", "async function callRecordings() {", "  head.appendChild(x);", "box", "x", "  ", 22),
    L("calOpen", "async function calOpen() {", "  head.appendChild(x);", "box", "x", "  ", 51),
    L("mixtapeLibrary", "async function mixtapeLibrary() {", "  head.appendChild(x);", "box", "x", "  ", 20),
    L("djGraphPanel", "function djGraphPanel() {", "  head.appendChild(shut);", "rail", "shut", "  ", 38),
    L("mindOpen", "function mindOpen(opts) {", "  bar.appendChild(shut);", "stage", "shut", "  ", 172),
    L("glassOpen", "function glassOpen() {", "  head.appendChild(shut);", "box", "shut", "  ", 40),
    L("backlogOpen", "function backlogOpen() {", "  head.appendChild(shut);", "box", "shut", "  ", 26),
    L("slotOpen", "async function slotOpen() {", "  head.appendChild(shut);", "box", "shut", "  ", 22),
    L("wedgeConsoleOpen", "async function wedgeConsoleOpen() {", "  head.appendChild(shut);", "box", "shut", "  ", 31),
    L("fixDrawerBuild", "function fixDrawerBuild() {", "  head.appendChild(shut);", "box", "shut", "  ", 24),
    L("sfxDeskPanel", "async function sfxDeskPanel() {", "  head.appendChild(shut);", "box", "shut", "  ", 24),
    L("paperReadOpen", "function paperReadOpen(url, label) {", "  top.appendChild(shut);", "card", "shut", "  ", 37),
    L("paperOpen", "async function paperOpen() {", "  [copy, pdf, image, hourly, older, newer, print, open, bin, x].forEach((b) => head.appendChild(b));", "box", "x", "  ", 108),
    L("screenplayOpen", "async function screenplayOpen() {", "  [copy, md, pdf, note, again, x].forEach((b) => head.appendChild(b));", "box", "x", "  ", 38),
    L("cupboardPanel", "async function cupboardPanel() {", "  stage.appendChild(close);", "shade", "close", "  ", 43),
    L("phonePanel", "async function phonePanel() {", "  stage.appendChild(close);", "shade", "close", "  ", 32),
    L("rapAssemblyPanel", "async function rapAssemblyPanel() {", "  stage.appendChild(close);", "shade", "close", "  ", 32),
    L("orchLogicPanel", "async function orchLogicPanel() {", "  stage.appendChild(close);", "shade", "close", "  ", 35),
    L("orchPlexusOpen", "async function orchPlexusOpen() {", "  bar.appendChild(x);", "glass", "x", "  ", 174),
    L("orchOpen", "async function orchOpen() {", "  bar.appendChild(shut);", "box", "shut", "  ", 26),
    L("chunkOpen", "async function chunkOpen() {", "  head.appendChild(shut);", "box", "shut", "  ", 26),
    L("crystalOpen", "async function crystalOpen() {", "  head.appendChild(shut);", "box", "shut", "  ", 34),
    L("winampOpen", "function winampOpen() {", "  bar.appendChild(shut);", "box", "shut", "  ", 123),
    L("studioOpen", "function studioOpen() {", "  title.appendChild(close);", "win", "close", "  ", 41),
    L("studioCookies", "async function studioCookies() {", "  head.appendChild(shut);", "card", "shut", "  ", 28),
]
PATCHES = [p for p in ROWS if p.marker.split(":")[2] not in SKIP]

if __name__ == "__main__":
    sys.exit(main(PATCHES))
