/* THE VIDEO WALL - what the station is making, moving.
 *
 * The gallery log already carries video and nobody was ever shown it.
 * MEASURED against data/generations.jsonl on 2026-09-11: 267 records, of
 * which 165 are `kind: "image"`, 60 are `kind: "paper"` (the Gazette's
 * hourly plates), 35 predate the `kind` field entirely - and SEVEN are
 * `kind: "video"`, every one of them rendered by `wan2.2_ti2v_5B_fp16`.
 * Six of those seven have a finished `.mp4` on disk. The LCD's gallery
 * deliberately drops them (lcd-gallery.js catalogue(): the extension test
 * is png|jpe?g|webp), because a 320x240 SPI display cannot decode video.
 * This screen can, so this is the one place they are visible at all.
 *
 * THE ROUTE CANNOT SEEK. /api/generations/image/{filename} (app.py:112044
 * - the plan cited 110873, which has drifted, and the route serves video
 * despite its name) reads the file off the /comfy-output bind mount and
 * answers with a plain Response carrying the whole body. There is no
 * Accept-Ranges, no 206, no seek. Pointing a <video src> at it and hoping
 * is how you get a wall that stalls on one clip forever.
 *
 * So a clip is DOWNLOADED WHOLE and handed to the element as local bytes -
 * the same shape the sampler uses for audio (sampler.js fetchBytes). Three
 * things fall out of that and all three are the point:
 *   - the byte length is known BEFORE anything decodes, so an oversized
 *     clip can be refused with a reason rather than buffering the wall to
 *     a stop;
 *   - a zero-length file is a fact, not a black rectangle that looks like
 *     a dead panel;
 *   - once it is local it seeks, loops and restarts for free.
 *
 * ONLY THE CURRENT AND NEXT CLIP ARE HELD, which is the discipline the LCD
 * gallery already runs on (docs/pine-box-lcd.md:21) and it matters more
 * here: a decoded second of video is orders of magnitude bigger than a
 * decoded picture, and this view is also meant to run on a 4 GB MediaTek
 * tablet. Every clip that leaves is RELEASED, including on destroy - an
 * object URL that is never revoked is a leak the browser will not collect.
 *
 * TWO THINGS MAKE IT MEAN SOMETHING RATHER THAN JUST MOVE.
 *
 * 1. RECENCY. A clip's weight halves every twelve hours, so the wall shows
 *    what the station is making NOW. It never reaches zero: an old clip
 *    keeps a floor weight, because a wall that can only ever show today is
 *    dark on a quiet morning.
 *
 * 2. ACTIVITY. Honest note, because this is the part it would be easy to
 *    fake: THE GENERATION LOG HAS NO ACTIVITY FIELD. A record is
 *    {ts, request, tags, model, prompt_id, files, status, kind, stats}
 *    (app.py:6966) and `tags` is the render PROMPT, not a label - #1158's
 *    Gazette rows are the one exception, where the tags genuinely begin
 *    "gazette <edition>". So attribution here is DERIVED from evidence
 *    that is actually in the row, and says which evidence it used:
 *      - kind/model say `paper`/`gazette`      -> the Gazette
 *      - the request is the gallery's own      -> regenerated by hand
 *      - a booth name from the live /api/dj    -> that DJ, on air
 *      - the word orchestrator appears         -> the orchestrator
 *      - anything else                         -> station work
 *    Nothing is claimed that the row does not say. The booth names are
 *    passed in from the SAME station poll the rest of the view runs on
 *    (dj_names, app.py:25275), so the wall follows a cast change with no
 *    request of its own.
 *
 * There is not one timer in this file. It is driven entirely by tick(),
 * which the view calls from the shared 250ms interpolation beat - the
 * single-poller rule (app.py:154692), which this view is the biggest risk
 * to, because 38 concurrent requests in flight to this station measured a
 * 46-second media stall on the tablet.
 */
(function (root) {
  "use strict";

  const CATALOGUE = "/api/generations?limit=1000";
  const CLIP = "/api/generations/image/";

  /* The catalogue is re-read at most once a minute, matching the LCD
   * gallery. A render takes 84-102s on this box (stats.duration_s, the
   * seven video rows), so a faster read could not find anything newer. */
  const REFRESH_MS = 60000;

  /* A failed clip rests before anything tries it again, and a failure
   * never schedules its own retry - the next attempt waits for a later
   * tick. This is what stops a 404 turning into a request loop. */
  const FAIL_REST_MS = 60000;
  const RETRY_MS = 250;

  /* No Range means the whole file is on the wire before a frame shows, so
   * length is a hard limit rather than a preference. A WAN 5B clip off
   * this station is a few MB; anything past this is not a short clip and
   * is refused by name so the operator can see WHICH file is the problem. */
  const MAX_BYTES = 24 * 1024 * 1024;

  /* And a clip that somehow is long gets taken off the wall anyway. The
   * element's own `ended` is the normal way one finishes; this is the
   * backstop for a file that never does. */
  const MAX_CLIP_MS = 60000;

  const HALF_LIFE_MS = 12 * 3600 * 1000;
  const WEIGHT_FLOOR = 0.02;

  const VIDEO = /\.(mp4|webm)$/i;
  /* STILLS COUNT AS CONTENT.
   *
   * "Make sure content is always streaming to the wall or any of these
   * slideshow views that I'm needing to see."
   *
   * Measured on the live station: /api/generations returned 40 entries and
   * 40 files, and ZERO of them were clips - every one a .png. So the wall
   * filtered the whole gallery away, had nothing to play, and sat on the
   * loading plexus indefinitely. It was behaving correctly and showing
   * nothing, which is the worst combination: no error to chase and no
   * picture either.
   *
   * A still costs far less than a clip - no blob, no Range problem, no
   * decoded video held in memory - so the discipline that limits clips to
   * one in flight does not need to apply to them. */
  const STILL = /\.(png|jpe?g|webp|gif)$/i;

  /* Same filename discipline as lcd-gallery.js: the station guards this
   * route too (app.py:112051 rejects a slash, a .. or anything outside
   * [\w.\- ()\[\]]), but a client that sends one anyway is a client with a
   * bug, and the wall should not be the thing that finds out. */
  function usableName(name) {
    return typeof name === "string"
      && name.length > 0 && name.length <= 200
      && !name.includes("..")
      /* By code point rather than by a regex literal: 47 and 92 are the
       * two slashes, anything under 32 and 127 are the controls. */
      && !Array.from(name).some((ch) => {
        const code = ch.charCodeAt(0);
        return code < 32 || code === 47 || code === 92 || code === 127;
      })
      && (VIDEO.test(name) || STILL.test(name));
  }

  function kindOf(name) { return VIDEO.test(name) ? "clip" : "still"; }

  function text(value) { return String(value == null ? "" : value); }

  /* WHOSE WORK IS THIS. See the header: derived from what the row says,
   * never invented. `names` is the live cast off /api/dj dj_names. */
  function activityOf(row, names) {
    const kind = text(row && row.kind).toLowerCase();
    const model = text(row && row.model).toLowerCase();
    if (kind === "paper" || model === "gazette") {
      return { key: "gazette", label: "the Gazette" };
    }
    const said = (text(row && row.request) + " " + text(row && row.tags)).toLowerCase();
    if (/^regenerated from gallery/i.test(text(row && row.request))) {
      return { key: "gallery", label: "regenerated by hand" };
    }
    for (const [seat, name] of Object.entries(names || {})) {
      const who = text(name).trim();
      if (!who || who.length < 3) continue;
      /* Whole word only. "Pine" inside "Pinebox" is not the co-host. */
      const pattern = new RegExp("(^|[^a-z0-9])"
        + who.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
        + "([^a-z0-9]|$)");
      if (pattern.test(said)) {
        return { key: "booth", label: who + " on air", seat };
      }
    }
    if (said.includes("orchestrator")) {
      return { key: "orchestrator", label: "the orchestrator" };
    }
    return { key: "station", label: "station work" };
  }

  /* Halves every twelve hours, never reaches zero. A row with no usable
   * timestamp is treated as the oldest thing on the shelf rather than the
   * newest, which is the safe way round for a wall that is meant to show
   * what is happening now. */
  function weightAt(ts, at) {
    const stamp = Number(ts);
    if (!Number.isFinite(stamp) || stamp <= 0) return WEIGHT_FLOOR;
    const age = Math.max(0, at - stamp * 1000);
    return WEIGHT_FLOOR + (1 - WEIGHT_FLOOR) * Math.pow(2, -age / HALF_LIFE_MS);
  }

  /* Newest first, one entry per file, clips and stills. `status: "lost"` rows
   * are dropped: three of the 267 measured rows carry it and it means
   * ComfyUI never handed the file over, so the name would 404 forever. */
  function catalogue(payload, at, names) {
    const rows = payload && Array.isArray(payload.generations)
      ? payload.generations : [];
    const seen = new Set();
    const out = [];
    for (const row of rows) {
      if (!row || !Array.isArray(row.files)) continue;
      if (text(row.status).toLowerCase() === "lost") continue;
      const activity = activityOf(row, names);
      for (const name of row.files) {
        if (!usableName(name) || seen.has(name)) continue;
        seen.add(name);
        out.push({
          file: name,
          kind: kindOf(name),
          ts: Number(row.ts) || 0,
          weight: weightAt(row.ts, at),
          activity: activity.key,
          label: activity.label,
          model: text(row.model),
          request: text(row.request).slice(0, 200),
          /* Kept so the attribution can be worked out AGAIN when the cast
           * changes, without asking the station for the log a second
           * time. Bounded, because the whole shelf sits in memory. */
          raw: {
            kind: text(row.kind),
            model: text(row.model),
            request: text(row.request).slice(0, 400),
            tags: text(row.tags).slice(0, 400)
          }
        });
      }
    }
    out.sort((a, b) => b.ts - a.ts);
    return out;
  }

  /* A weighted draw. Sorted newest-first above, so a low roll lands on
   * recent work and a high one reaches the back of the shelf - which is
   * also what makes this testable with a fixed random(). */
  function weighted(rows, roll) {
    if (!rows.length) return null;
    let total = 0;
    for (const row of rows) total += row.weight;
    if (!(total > 0)) return rows[0];
    let point = Math.min(0.9999999, Math.max(0, Number(roll) || 0)) * total;
    for (const row of rows) {
      point -= row.weight;
      if (point < 0) return row;
    }
    return rows[rows.length - 1];
  }

  function create(options) {
    /* Set by setMode. It used to mean "stand down": with the wall able to
     * show clips only, "stills" left nothing for it to do. Now that stills
     * are content it can draw, the mode picks a pool instead of switching
     * the wall off, and `paused` is reserved for a genuinely idle wall. */
    let paused = false;
    let mode = "clips";
    const settings = options || {};
    const get = settings.get;
    const fetchClip = settings.fetchClip;
    if (typeof get !== "function" || typeof fetchClip !== "function") {
      throw new Error("The video wall needs the station's bridge.");
    }
    const releaseClip = typeof settings.releaseClip === "function"
      ? settings.releaseClip : () => {};
    const random = typeof settings.random === "function" ? settings.random : Math.random;
    const clock = typeof settings.now === "function" ? settings.now : Date.now;
    const maxBytes = Number(settings.maxBytes) > 0 ? Number(settings.maxBytes) : MAX_BYTES;
    const maxClipMs = Number(settings.maxClipMs) > 0 ? Number(settings.maxClipMs) : MAX_CLIP_MS;

    let shelf = [];
    let names = {};
    let current = null;      /* {file, clip, activity, label, at} */
    let upcoming = null;
    let loading = false;
    let fetching = null;
    let fetched = false;
    let lastRefresh = -Infinity;
    let retryAt = 0;
    let destroyed = false;
    let error = "";
    let note = "";
    let revision = 0;
    const failed = new Map();

    const at = () => {
      const value = Number(clock());
      return Number.isFinite(value) ? value : Date.now();
    };

    function release(row) {
      if (!row || !row.clip) return;
      try { releaseClip(row.clip); } catch (err) { /* a leak beats a crash */ }
    }

    const eligible = (name) => name !== (current && current.file)
      && name !== (upcoming && upcoming.file)
      && (!failed.has(name) || at() - failed.get(name) >= FAIL_REST_MS);

    /* WHAT THE WALL MAY DRAW FROM, given the mode - and the fallback that
     * keeps something on screen.
     *
     * "clips"  is a preference, not a vow: with no clips on the shelf the
     * choice is a still or a blank rectangle, and a blank rectangle is not
     * what was asked for. So an empty clip shelf falls through to stills
     * in every mode except an explicit "stills", which is already stills. */
    function candidate() {
      const open = shelf.filter((row) => eligible(row.file));
      if (!open.length) return null;
      const clips = open.filter((row) => row.kind === "clip");
      const stills = open.filter((row) => row.kind === "still");
      let pool;
      if (mode === "stills") pool = stills;
      else if (mode === "clips") pool = clips.length ? clips : stills;
      else pool = clips.length ? clips : stills;   /* "both" */
      if (!pool.length) pool = open;
      return weighted(pool, random());
    }

    /* ONE clip in flight, ever. The whole reason this module exists is
     * that many panes on one screen must not become many requests. */
    function pump() {
      if (destroyed || loading || upcoming || at() < retryAt) return;
      if (current && shelf.length <= 1) return;   /* one clip: it loops */
      const row = candidate();
      if (!row) return;
      loading = true;
      Promise.resolve()
        .then(() => (row.kind === "still"
          /* Straight off the route. The gallery serves images with open
           * read auth and no Range problem, so there is nothing to
           * download whole and nothing to revoke afterwards. */
          ? {src: CLIP + encodeURIComponent(row.file), bytes: 1, still: true}
          : fetchClip(CLIP + encodeURIComponent(row.file))))
        .then((clip) => {
          const held = { ...row, clip, at: at() };
          if (destroyed) { release(held); return; }
          const bytes = Number(clip && clip.bytes);
          /* An empty file is the failure that looks most like success:
           * the request is 200, the element is handed a valid object URL,
           * and the wall goes black with no error anywhere. Name it. */
          if (!Number.isFinite(bytes) || bytes <= 0) {
            release(held);
            throw new Error(row.file + " is an empty file - nothing was rendered into it.");
          }
          if (bytes > maxBytes) {
            release(held);
            throw new Error(row.file + " is "
              + Math.round(bytes / (1024 * 1024)) + " MB. That route has no "
              + "Range support, so a clip that long cannot be held or seeked.");
          }
          failed.delete(row.file);
          note = "";
          retryAt = 0;
          if (!current) { current = held; revision += 1; }
          else upcoming = held;
        })
        .catch((reason) => {
          if (destroyed) return;
          failed.set(row.file, at());
          retryAt = at() + RETRY_MS;
          note = String((reason && reason.message) || "That clip is unavailable.");
        })
        .finally(() => {
          loading = false;
          /* A success may go straight on to fill the second slot. A
           * FAILURE waits for the next tick, so even an instant 404 on
           * every clip cannot spin. */
          if (!destroyed && !note) pump();
        });
    }

    function refresh(force) {
      if (destroyed) return Promise.resolve();
      if (fetching) return fetching;
      if (!force && at() - lastRefresh < REFRESH_MS) return Promise.resolve();
      lastRefresh = at();
      fetching = Promise.resolve()
        .then(() => get(CATALOGUE))
        .then((payload) => {
          if (destroyed) return;
          shelf = catalogue(payload, at(), names);
          fetched = true;
          error = "";
          const live = new Set(shelf.map((row) => row.file));
          for (const name of [...failed.keys()]) if (!live.has(name)) failed.delete(name);
          /* A clip deleted out from under us is dropped BEFORE it is
           * shown, never while it is showing - pulling the current one
           * would blank the wall for no reason the operator can see. */
          if (upcoming && !live.has(upcoming.file)) { release(upcoming); upcoming = null; }
          pump();
        })
        .catch((reason) => {
          if (destroyed) return;
          /* ComfyUI being down is the common case and it must not take
           * the wall with it: whatever is already playing keeps playing,
           * and the reason is on screen rather than in a console. */
          error = String((reason && reason.message) || "The gallery is unavailable.");
        })
        .finally(() => { fetching = null; });
      return fetching;
    }

    /* The element's `ended` calls this, and so does the backstop below. */
    function advance() {
      if (destroyed || !current) return;
      if (!upcoming) { current.at = at(); revision += 1; return; }   /* loop it */
      release(current);
      current = upcoming;
      upcoming = null;
      current.at = at();
      revision += 1;
      pump();
    }

    function state() {
      return {
        ready: !!current,
        file: current ? current.file : "",
        kind: current ? (current.kind || "clip") : "",
        still: !!(current && current.kind === "still"),
        clips: shelf.filter((row) => row.kind === "clip").length,
        stills: shelf.filter((row) => row.kind === "still").length,
        clip: current ? current.clip : null,
        activity: current ? current.activity : "",
        label: current ? current.label : "",
        request: current ? current.request : "",
        total: shelf.length,
        holding: (current ? 1 : 0) + (upcoming ? 1 : 0),
        next: upcoming ? upcoming.file : "",
        revision,
        error,
        note,
        state: current ? "playing"
          : error ? "error"
            : loading || fetching || !fetched ? "loading"
              : note ? "error" : "empty"
      };
    }

    return {
      /* Driven from the view's shared beat. No timer of its own. */
      tick(stamp) {
        if (destroyed || paused) return state();
        refresh();
        const mark = Number.isFinite(Number(stamp)) ? Number(stamp) : at();
        if (current && mark - current.at >= maxClipMs) advance();
        pump();
        return state();
      },
      refresh,
      advance,
      state,

      /* WHAT THE WALL IS ALLOWED TO SHOW.
       *
       * "If I tap on the picture, allow me to cycle between it being a
       * slideshow of just videos or videos and images."
       *
       * This module catalogues clips and stills. Only clips are fetched and
       * held as blobs; stills use the station route directly, so switching
       * pools does not add decoded video pressure on the tablet.
       *
       *   clips          -> clips, falling back to stills when no clips exist
       *   both           -> prefer clips, then stills
       *   stills         -> stills only
       */
      setMode(next) {
        const want = String(next || "clips");
        if (want === mode) return want;
        mode = want;
        paused = false;
        /* The pool has changed under the current picture, so let it go and
         * draw again from the new one - otherwise "stills" keeps showing
         * the clip that was already up until it happens to end. */
        if (current) {
          if (current.clip && !current.clip.still) {
            try { release(current); } catch (err) { /* gone */ }
          }
          current = null;
          revision += 1;
        }
        return want;
      },
      /* Which pool it is drawing from, for the readout. */
      mode() { return mode; },
      /* The cast off the same /api/dj poll everything else reads. */
      cast(next) {
        const wanted = JSON.stringify(next || {});
        if (wanted === JSON.stringify(names)) return;
        names = Object.assign({}, next || {});
        shelf = shelf.map((row) => {
          const found = activityOf(row.raw || {}, names);
          return { ...row, activity: found.key, label: found.label };
        });
        /* What is ON the wall keeps the label it was put up with. Relabelling
         * a clip mid-play would make the caption contradict the picture. */
      },
      shelf() { return shelf.slice(); },
      destroy() {
        destroyed = true;
        release(current); release(upcoming);
        current = null; upcoming = null;
        shelf = []; failed.clear();
      }
    };
  }

  const api = { create, catalogue, activityOf, weightAt, weighted, usableName,
    MAX_BYTES, HALF_LIFE_MS, WEIGHT_FLOOR };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.PineVideoWall = api;
})(typeof window !== "undefined" ? window : globalThis);
