"""[h3-prompts] The hourly H3 render's words are presets the operator saves,
cycles and rolls - from the Pine Box Gallery's P and dice.

"Put an option here of a P for prompt and whenever I click it or tap it it
takes me to a screen where I'm able to modify the prompts that are used for the
hourly generation. I want to be able to save and cycle through presets ... And
then I also want a dice icon that if I click it, it actually shuffles between
the prompts that I have saved ... I want to be able to also be able to see the
prompts used with a video on the main gallery popup" (operator, 2026-09-28).

The hourly door's words (h3_hourly_ad_prompt's brief; the clip, gallery and
host roads' directions) become the first preset, "Default", so nothing changes
until the operator acts. data/h3_prompt_presets.json keeps the presets, the
active one, the dice, the pin for the next hour and a week of hours; GET/POST
/api/h3/prompts[/active|/dice|/next|/{id}|/{id}/delete], GET
/api/h3/prompts/history. Each hour: the pin, else (dice on) System 3's roll
among the presets (POOLS1 row h3.hourly_preset), else the active preset. The
clip road takes its words in voice_ad_render; a queued host / gallery render
takes them at dispatch (h3_prompts_dress); the words, preset and roll ride the
generation row as `h3_prompts` (and `hourly`), which the gallery shows under
the video. No render is added or moved (#1285).

Every anchor sits outside the text other tools store (tools/*.py): the hourly
render itself (h3_hourly_door / h3_cast / h3_fresh) is not edited.

--check exits 0 ready / 2 applied / 1 missing. ON THE HOST.
"""
import os
import sys
import tempfile
from pathlib import Path

EDITS = [
    ("hourly-brief-is-the-preset",
     '    return ("Make a short, funny but professional Pine Box FM sponsor stinger "\n'
     '            "that naturally follows this hour\'s conversation: " + subject[:520])\n',
     "    # [h3-prompts] in the words of the hour's preset: the one pinned for the\n"
     "    # next hour, else the gallery's dice (System 3 rolls a saved preset), else\n"
     '    # the active one - "Default" is the brief this always was. The roads take\n'
     '    # their directions from the same hour (h3_prompts_hour_for).\n'
     '    return h3_prompts_hour(subject[:520], " ".join(record.split()))["goal"]\n', 1),
    ("clip-road-line",
     '    if not copy:\n'
     '        copy = voice_ad_spoken_copy(goal)\n',
     '    if not copy:\n'
     '        copy = voice_ad_spoken_copy(goal)\n'
     "    # [h3-prompts] the hourly clip road is told the hour's preset: its clip\n"
     '    # direction and its line (blank: the line pulled out of the brief, above)\n'
     '    _h3_words = None\n'
     '    if hourly:\n'
     '        _h3_hour = h3_prompts_hour_for(goal, exact=True)\n'
     '        if _h3_hour is not None:\n'
     '            _h3_words = h3_prompts_words(_h3_hour, "clip", copy)\n'
     '            copy = _h3_words["speech"]\n'
     '            h3_prompts_claim(_h3_hour)\n', 1),
    ("clip-road-direction",
     '                 "energy, and clean synchronized dialogue. No captions or logos.")\n',
     '                 "energy, and clean synchronized dialogue. No captions or logos.")\n'
     '    if _h3_words is not None:\n'
     '        direction = _h3_words["direction"]                 # [h3-prompts] the preset\'s clip road\n', 1),
    ("clip-road-payload",
     '            "duration_mode": "at_least", "air_it": True,\n',
     '            "duration_mode": "at_least", "air_it": True,\n'
     '            **h3_prompts_payload_keys(_h3_words),              # [h3-prompts] style, audio, constraints, record\n', 1),
    ("generation-row-keeps-the-words",
     '                "sequence_part", "sequence_parts", "trim_in_s", "trim_out_s"):\n',
     '                "sequence_part", "sequence_parts", "trim_in_s", "trim_out_s",\n'
     '                "hourly", "h3_prompts"):          # [h3-prompts] the hour\'s words ride the row\n', 1),
    ("hourly-render-takes-the-preset",
     'async def _comfy_workshop_render_payload(payload: dict[str, Any]) -> dict[str, Any]:\n'
     '    if not isinstance(payload, dict):\n'
     '        raise HTTPException(status_code=400, detail="Expected an object")\n',
     'async def _comfy_workshop_render_payload(payload: dict[str, Any]) -> dict[str, Any]:\n'
     '    if not isinstance(payload, dict):\n'
     '        raise HTTPException(status_code=400, detail="Expected an object")\n'
     "    payload = h3_prompts_dress(payload)        # [h3-prompts] an hourly host / gallery render: the hour's preset\n", 1),
    ("compose-with-the-preset-brief",
     '    final_prompt = comfy_workshop.compose_prompt(\n',
     '    final_prompt = h3_prompts_compose(payload.get("h3_brief"),     # [h3-prompts] a preset\'s audio / constraints\n', 1),
    ("render-row-carries-the-words",
     '                          payload.get("variant_of") or payload.get("source_generation") or "")[:120],\n'
     '                      "air_it": bool(payload.get("air_it")),\n',
     '                          payload.get("variant_of") or payload.get("source_generation") or "")[:120],\n'
     '                      "air_it": bool(payload.get("air_it")),\n'
     '                      **({"hourly": True} if payload.get("hourly") else {}),          # [h3-prompts]\n'
     '                      **({"h3_prompts": payload["h3_prompts"]}\n'
     '                         if isinstance(payload.get("h3_prompts"), dict) else {}),\n', 1),
    ("presets-store-and-doors",
     '@app.on_event("startup")\n'
     'async def _parody_stinger_start() -> None:\n',
     '# --- [h3-prompts] THE HOURLY PROMPTS: PRESETS THE OPERATOR SAVES, CYCLES, ROLLS --\n'
     '#\n'
     '# "Put an option here of a P for prompt and whenever I click it or tap it it\n'
     "#  takes me to a screen where I'm able to modify the prompts that are used for\n"
     '#  the hourly generation. I want to be able to save and cycle through presets\n'
     '#  ... And then I also want a dice icon that if I click it, it actually\n'
     '#  shuffles between the prompts that I have saved ... I want to be able to also\n'
     '#  be able to see the prompts used with a video on the main gallery popup"\n'
     '#  (operator, 2026-09-28).\n'
     '#\n'
     '# A preset is every word the hourly H3 render is told: the brief (`goal` -\n'
     "# {conversation} is the hour's talk, {record} the record on air), a direction\n"
     '# for each road the hour can take (`clip`: a dialogue clip is the reference,\n'
     "# `gallery`: a gallery picture is, `host`: the host's LoRA presents - {goal} is\n"
     '# the brief, filled), the line spoken (blank: pulled out of the brief, as it\n'
     '# always was), one style term, and the audio direction and constraints (blank:\n'
     '# the gear\'s brief). Today\'s words are the first preset, "Default", so nothing\n'
     '# changes until the operator acts. Each hour takes the preset pinned for it\n'
     '# ("use for the next hour"), else - the gallery\'s dice on - the one System 3\n'
     '# rolls among the saved presets (POOLS1 row h3.hourly_preset: the desk weights\n'
     '# a preset or switches it off; the roll is recorded like every station roll),\n'
     "# else the active one. The hour lands in the store's history; the words ride\n"
     "# the video's own generation row (`h3_prompts`), shown under the video.\n"
     '#\n'
     '# Nothing here adds or moves a render - a second H3 render in one boot is what\n'
     '# cooks the box (#1285); it only changes what the one hourly render is told.\n'
     '# The store is read from memory without a lock; every write happens in a\n'
     '# worker thread under _H3_PROMPTS_LOCK and lands atomically.\n'
     '_H3_PROMPTS_FILE = DATA_DIR / "h3_prompt_presets.json"\n'
     '_H3_PROMPTS_LOCK = RLock()                      # worker threads only - never on the event loop\n'
     '_H3_PROMPTS_MEM: list[Any] = [None]             # the store as last read or written, swapped whole\n'
     '_H3_PROMPTS_HOURS: list[dict[str, Any]] = []    # the hours this process resolved, newest last\n'
     '_H3_PROMPTS_DRESSED: dict[str, list[float]] = {}   # hour -> [renders dressed, when last]\n'
     'H3_PROMPTS_FIELDS = ("goal", "clip", "gallery", "host", "speech", "style", "constraints", "audio_direction")\n'
     'H3_PROMPTS_ROADS = ("clip", "gallery", "host")\n'
     'H3_PROMPTS_LIMITS = {"name": 60, "goal": 1200, "clip": 1800, "gallery": 1800, "host": 1800,\n'
     '                     "speech": 700, "style": 120, "constraints": 400, "audio_direction": 400}\n'
     'H3_PROMPTS_DEFAULT = {\n'
     '    "goal": ("Make a short, funny but professional Pine Box FM sponsor stinger "\n'
     '             "that naturally follows this hour\'s conversation: {conversation}"),\n'
     '    "clip": ("Create a polished short Pine Box advertisement from the reference "\n'
     '             "performance. The person or people on screen must {goal}. Keep expressive "\n'
     '             "natural motion, direct-to-camera commercial energy, and clean synchronized "\n'
     '             "dialogue. No captions or logos."),\n'
     '    "gallery": ("Create a Pine Box FM stinger using the supplied image. Natural motion and "\n'
     '                "synchronized spoken dialogue. No captions or logos. {goal}"),\n'
     '    "host": ("The Pine Box host presents a Pine Box FM stinger at the station\'s desk, "\n'
     '             "direct to camera, in warm late-night studio light. {goal}"),\n'
     '    "speech": "", "style": "", "constraints": "", "audio_direction": ""}\n'
     'H3_PROMPTS_MOST = 60                  # saved presets\n'
     'H3_PROMPTS_HISTORY_KEEP = 168         # a week of hours\n'
     'H3_PROMPTS_FIND_S = 86400.0           # a queued hourly render finds its hour within a day\n'
     'H3_PROMPTS_DICE_KEY = "h3.hourly_preset"\n'
     'H3_PROMPTS_DICE_LABEL = "which saved prompt preset the hourly H3 video is told (the gallery\'s dice)"\n'
     '_H3_PROMPTS_ID = re.compile(r"[A-Za-z0-9_-]{1,40}")\n'
     '\n'
     '\n'
     'def _h3_prompts_text(value: Any, field: str) -> str:\n'
     '    """One field as the store keeps it: text, trimmed, within its limit. The\n'
     '    name and the one-line fields are one line; a brief or a direction keeps\n'
     '    its line breaks (compose_prompt joins them)."""\n'
     '    text = str(value if value is not None else "")\n'
     '    if field in ("name", "speech", "style", "constraints", "audio_direction"):\n'
     '        text = " ".join(text.split())\n'
     '    else:\n'
     '        text = "\\n".join(" ".join(line.split()) for line in text.replace("\\r", "").split("\\n")).strip()\n'
     '    return text[:H3_PROMPTS_LIMITS.get(field, 600)]\n'
     '\n'
     '\n'
     'def h3_prompts_fields(preset: Any) -> dict[str, str]:\n'
     '    """[h3-prompts] A preset\'s words, clean. A blank brief or road direction is\n'
     '    the Default\'s - a road always has words; the rest may stay blank."""\n'
     '    got = preset if isinstance(preset, dict) else {}\n'
     '    out = {field: _h3_prompts_text(got.get(field, ""), field) for field in H3_PROMPTS_FIELDS}\n'
     '    for field in ("goal",) + H3_PROMPTS_ROADS:\n'
     '        if not out[field]:\n'
     '            out[field] = H3_PROMPTS_DEFAULT[field]\n'
     '    return out\n'
     '\n'
     '\n'
     'def h3_prompts_fill(template: Any, **values: Any) -> str:\n'
     '    """The template with its {placeholders} filled. Plain replacement, so a\n'
     '    brace the operator types is only ever text."""\n'
     '    out = str(template or "")\n'
     '    for key, value in values.items():\n'
     '        out = out.replace("{" + key + "}", str(value or ""))\n'
     '    return out.strip()\n'
     '\n'
     '\n'
     'def _h3_prompts_stamp(value: Any, default: float) -> float:\n'
     '    try:\n'
     '        return round(float(value), 3)\n'
     '    except (TypeError, ValueError):\n'
     '        return round(default, 3)\n'
     '\n'
     '\n'
     'def _h3_prompts_preset(raw: Any, pid: str = "") -> dict[str, Any]:\n'
     '    """One stored preset: an id, a name, its words, when made and changed."""\n'
     '    got = raw if isinstance(raw, dict) else {}\n'
     '    now = time.time()\n'
     '    want = str(pid or got.get("id") or "")\n'
     '    out: dict[str, Any] = {"id": want if _H3_PROMPTS_ID.fullmatch(want) else "p-" + uuid.uuid4().hex[:10],\n'
     '                           "name": _h3_prompts_text(got.get("name"), "name") or "Untitled"}\n'
     '    out.update(h3_prompts_fields(got))\n'
     '    out["created_at"] = _h3_prompts_stamp(got.get("created_at"), now)\n'
     '    out["updated_at"] = _h3_prompts_stamp(got.get("updated_at"), out["created_at"])\n'
     '    return out\n'
     '\n'
     '\n'
     'def _h3_prompts_seed() -> dict[str, Any]:\n'
     '    """Today\'s words, as the first preset: nothing changes until the operator acts."""\n'
     '    return {"version": 1, "rev": 0, "active": "default", "dice": False, "next": None,\n'
     '            "presets": [_h3_prompts_preset(dict(H3_PROMPTS_DEFAULT, name="Default"), "default")],\n'
     '            "history": []}\n'
     '\n'
     '\n'
     'def _h3_prompts_pin(raw: Any) -> dict[str, Any] | None:\n'
     '    """The words pinned for the next hour, clean - or None."""\n'
     '    if not isinstance(raw, dict) or not isinstance(raw.get("preset"), dict):\n'
     '        return None\n'
     '    pid = str(raw.get("id") or "")\n'
     '    return {"id": pid if _H3_PROMPTS_ID.fullmatch(pid) else "n-" + uuid.uuid4().hex[:10],\n'
     '            "at": _h3_prompts_stamp(raw.get("at"), time.time()),\n'
     '            "from": str(raw.get("from") or "")[:40], "prompt_id": str(raw.get("prompt_id") or "")[:120],\n'
     '            "preset_id": str(raw.get("preset_id") or "")[:40],\n'
     '            "preset": _h3_prompts_preset(raw["preset"], str(raw["preset"].get("id") or "pinned"))}\n'
     '\n'
     '\n'
     'def _h3_prompts_normalise(got: Any) -> dict[str, Any]:\n'
     '    """The store as read: every preset clean, ids and names unique, the active\n'
     '    one among them, at least one preset (the Default when none is left)."""\n'
     '    store = _h3_prompts_seed()\n'
     '    if not isinstance(got, dict):\n'
     '        return store\n'
     '    presets: list[dict[str, Any]] = []\n'
     '    ids: set[str] = set()\n'
     '    names: set[str] = set()\n'
     '    for raw in list(got.get("presets") or [])[:H3_PROMPTS_MOST]:\n'
     '        if not isinstance(raw, dict):\n'
     '            continue\n'
     '        one = _h3_prompts_preset(raw)\n'
     '        if one["id"] in ids:\n'
     '            one["id"] = "p-" + uuid.uuid4().hex[:10]\n'
     '        base, n = one["name"], 2\n'
     '        while one["name"].lower() in names:\n'
     '            one["name"] = ("%s (%d)" % (base, n))[:H3_PROMPTS_LIMITS["name"]]\n'
     '            n += 1\n'
     '        ids.add(one["id"])\n'
     '        names.add(one["name"].lower())\n'
     '        presets.append(one)\n'
     '    if presets:\n'
     '        store["presets"] = presets\n'
     '    active = str(got.get("active") or "")\n'
     '    store["active"] = active if any(p["id"] == active for p in store["presets"]) else store["presets"][0]["id"]\n'
     '    store["dice"] = bool(got.get("dice"))\n'
     '    store["next"] = _h3_prompts_pin(got.get("next"))\n'
     '    store["history"] = [h for h in list(got.get("history") or []) if isinstance(h, dict)][-H3_PROMPTS_HISTORY_KEEP:]\n'
     '    try:\n'
     '        store["rev"] = max(0, int(got.get("rev") or 0))\n'
     '    except (TypeError, ValueError):\n'
     '        store["rev"] = 0\n'
     '    return store\n'
     '\n'
     '\n'
     'def h3_prompts_load(fresh: bool = False) -> dict[str, Any]:\n'
     '    """[h3-prompts] The store, read from disk once - in a worker thread (the\n'
     '    startup hook and every door call it through asyncio.to_thread)."""\n'
     '    with _H3_PROMPTS_LOCK:\n'
     '        if isinstance(_H3_PROMPTS_MEM[0], dict) and not fresh:\n'
     '            return _H3_PROMPTS_MEM[0]\n'
     '        store = _h3_prompts_seed()\n'
     '        try:\n'
     '            store = _h3_prompts_normalise(json.loads(_H3_PROMPTS_FILE.read_text(encoding="utf-8")))\n'
     '        except FileNotFoundError:\n'
     '            pass\n'
     '        except Exception as exc:  # noqa: BLE001\n'
     '            pipeline_log("ads", "hourly H3 prompt presets unreadable (%s): the Default preset stands in; "\n'
     '                                "the file is kept beside it as .unreadable" % type(exc).__name__)\n'
     '            try:\n'
     '                shutil.copyfile(_H3_PROMPTS_FILE, _H3_PROMPTS_FILE.with_name(_H3_PROMPTS_FILE.name + ".unreadable"))\n'
     '            except OSError:\n'
     '                pass\n'
     '        _H3_PROMPTS_MEM[0] = store\n'
     '        return store\n'
     '\n'
     '\n'
     'def _h3_prompts_write(store: dict[str, Any]) -> dict[str, Any]:\n'
     '    """The whole store, atomically: a temporary file, then a rename. Under the lock."""\n'
     '    store["rev"] = int(store.get("rev") or 0) + 1\n'
     '    store["saved_at"] = round(time.time(), 3)\n'
     '    tmp = _H3_PROMPTS_FILE.with_name(_H3_PROMPTS_FILE.name + ".tmp")\n'
     '    tmp.write_text(json.dumps(store, indent=1), encoding="utf-8")\n'
     '    os.replace(tmp, _H3_PROMPTS_FILE)\n'
     '    _H3_PROMPTS_MEM[0] = store\n'
     '    return store\n'
     '\n'
     '\n'
     'def h3_prompts_change(fn: Any) -> dict[str, Any]:\n'
     '    """[h3-prompts] Change the store: `fn` edits a copy, the copy is written and\n'
     '    becomes the store (an error in `fn` writes nothing). A worker thread, under\n'
     '    the lock - never on the event loop."""\n'
     '    with _H3_PROMPTS_LOCK:\n'
     '        store = copy.deepcopy(h3_prompts_load())\n'
     '        fn(store)\n'
     '        return _h3_prompts_write(store)\n'
     '\n'
     '\n'
     'def _h3_prompts_offloop(fn: Any, *args: Any) -> None:\n'
     '    """Hand a store write to a worker thread when called on the event loop; run\n'
     '    it here when there is no loop in this thread (a worker, a test)."""\n'
     '    try:\n'
     '        loop = asyncio.get_running_loop()\n'
     '    except RuntimeError:\n'
     '        fn(*args)\n'
     '        return\n'
     '    loop.run_in_executor(None, fn, *args)\n'
     '\n'
     '\n'
     'def h3_prompts_desk() -> dict[str, Any] | None:\n'
     '    """The POOLS1 row the dice tabled for the presets, as System 3\'s desk holds\n'
     '    it now (read-only) - None until the first roll has tabled it."""\n'
     '    getter = globals().get("_system3")\n'
     '    try:\n'
     '        config = getter().config if callable(getter) else {}\n'
     '    except Exception:  # noqa: BLE001\n'
     '        return None\n'
     '    for table in (config or {}).get("tables") or []:\n'
     '        if not isinstance(table, dict) or table.get("family") != "POOL" or table.get("enabled") is False:\n'
     '            continue\n'
     '        for cat in table.get("categories") or []:\n'
     '            if isinstance(cat, dict) and cat.get("id") == H3_PROMPTS_DICE_KEY:\n'
     '                return cat\n'
     '    return None\n'
     '\n'
     '\n'
     'def h3_prompts_weights(presets: list[dict[str, Any]], desk: dict[str, Any] | None) -> list[float]:\n'
     '    """Each preset\'s weight on the desk\'s row: a preset switched off there (or at\n'
     '    weight 0) sits out; one the desk has not seen - saved since the row was\n'
     '    tabled - rides at weight 1, as the dice door weighs any option it has not\n'
     '    seen."""\n'
     '    items = {" ".join(str(i.get("text") or "").split()): i\n'
     '             for i in (desk or {}).get("items") or [] if isinstance(i, dict)}\n'
     '    out = []\n'
     '    for preset in presets:\n'
     '        item = items.get(" ".join(str(preset.get("name") or "").split()))\n'
     '        if item is None:\n'
     '            out.append(1.0)\n'
     '        elif item.get("enabled") is False:\n'
     '            out.append(0.0)\n'
     '        else:\n'
     '            try:\n'
     '                out.append(max(0.0, float(item.get("weight", 1.0) or 0)))\n'
     '            except (TypeError, ValueError):\n'
     '                out.append(1.0)\n'
     '    return out\n'
     '\n'
     '\n'
     'def h3_prompts_roll(presets: list[dict[str, Any]], active: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:\n'
     '    """[h3-prompts] The gallery\'s dice: System 3 rolls which saved preset this\n'
     '    hour is told. The first roll tables the presets as a POOLS1 row\n'
     "    (h3.hourly_preset); the roll is System 3's own record, in the station's\n"
     '    rolls. With System 3 off the station rolls its own, evenly."""\n'
     '    if len(presets) < 2:\n'
     '        return active, {"by": "none", "why": "one saved preset - nothing to shuffle",\n'
     '                        "picked": str(active.get("name") or ""), "index": 1, "of": 1}\n'
     '    weights = [1.0] * len(presets)\n'
     '    if _s3_dice_live():\n'
     '        s3_pool(H3_PROMPTS_DICE_KEY, [p["name"] for p in presets], H3_PROMPTS_DICE_LABEL)\n'
     '        weights = h3_prompts_weights(presets, h3_prompts_desk())\n'
     '    cands = [(p, w) for p, w in zip(presets, weights) if w > 0]\n'
     '    if not cands:\n'
     '        return active, {"by": "desk", "why": "every preset is switched off on System 3\'s desk - the active one",\n'
     '                        "picked": str(active.get("name") or ""), "index": 0, "of": 0}\n'
     '    labels = [str(p["name"]) for p, _w in cands]\n'
     '    k = s3_weighted(H3_PROMPTS_DICE_KEY, labels, [w for _p, w in cands], H3_PROMPTS_DICE_LABEL)\n'
     '    k = k if isinstance(k, int) and 0 <= k < len(cands) else 0\n'
     '    rec = _s3_sfx_rolled(H3_PROMPTS_DICE_KEY, labels[k], k)\n'
     '    return cands[k][0], {"by": "system3" if rec else "station", "key": H3_PROMPTS_DICE_KEY,\n'
     '                         "picked": labels[k], "index": k + 1, "of": len(cands),\n'
     '                         "dice": rec.get("dice"), "u": rec.get("u"),\n'
     '                         "candidates": labels[:24], "weights": [round(w, 3) for _p, w in cands][:24]}\n'
     '\n'
     '\n'
     'def h3_prompts_how(entry: Any) -> str:\n'
     '    """How an hour came by its preset, in words."""\n'
     '    got = entry if isinstance(entry, dict) else {}\n'
     '    roll = got.get("roll") if isinstance(got.get("roll"), dict) else {}\n'
     '    if got.get("how") == "next":\n'
     '        return "pinned for the hour"\n'
     '    if got.get("how") == "dice":\n'
     '        if roll.get("by") == "system3":\n'
     '            return "rolled by System 3: d100 %s, %s of %s" % (roll.get("dice"), roll.get("index"), roll.get("of"))\n'
     '        if roll.get("by") == "station":\n'
     '            return "rolled by the station (System 3 off): %s of %s" % (roll.get("index"), roll.get("of"))\n'
     '        return "dice on, " + str(roll.get("why") or "no roll")\n'
     '    return "the active preset"\n'
     '\n'
     '\n'
     'def h3_prompts_hour(conversation: str, record: str = "") -> dict[str, Any]:\n'
     '    """[h3-prompts] This hour\'s preset, and its brief filled: the one pinned for\n'
     "    the next hour, else the dice's roll (the gallery's dice on), else the active\n"
     '    one. The hourly render calls this on the event loop (h3_hourly_ad_prompt):\n'
     "    it reads the store from memory and never takes the lock; the hour's record\n"
     '    is written off the loop."""\n'
     '    store = _H3_PROMPTS_MEM[0] if isinstance(_H3_PROMPTS_MEM[0], dict) else None\n'
     '    if store is None:              # the startup load has not landed: never read the disk on the loop\n'
     '        pipeline_log("ads", "hourly H3 prompts: the presets are not loaded yet - the Default preset\'s words")\n'
     '        store = _h3_prompts_seed()\n'
     '    presets = list(store.get("presets") or []) or _h3_prompts_seed()["presets"]\n'
     '    active = next((p for p in presets if p.get("id") == store.get("active")), presets[0])\n'
     '    pin = store.get("next") if isinstance(store.get("next"), dict) else None\n'
     '    roll = None\n'
     '    if pin and isinstance(pin.get("preset"), dict):\n'
     '        how = "next"\n'
     '        preset = next((p for p in presets if pin.get("preset_id") and p.get("id") == pin.get("preset_id")),\n'
     '                      pin["preset"])\n'
     '    elif store.get("dice"):\n'
     '        how = "dice"\n'
     '        preset, roll = h3_prompts_roll(presets, active)\n'
     '    else:\n'
     '        how, preset = "active", active\n'
     '    fields = h3_prompts_fields(preset)\n'
     '    goal = (h3_prompts_fill(fields["goal"], conversation=conversation, record=record)\n'
     '            or h3_prompts_fill(H3_PROMPTS_DEFAULT["goal"], conversation=conversation, record=record))\n'
     '    entry = {"hour": "h3h-" + uuid.uuid4().hex[:12], "at": round(time.time(), 3),\n'
     '             "marker": time.strftime("%Y%m%d%H"), "how": how,\n'
     '             "preset": {"id": str(preset.get("id") or ""), "name": str(preset.get("name") or "")},\n'
     '             "roll": roll, "pin": str((pin or {}).get("id") or "") if how == "next" else "",\n'
     '             "fields": fields, "conversation": str(conversation or "")[:600], "record": str(record or "")[:200],\n'
     '             "goal": goal}\n'
     '    _H3_PROMPTS_HOURS.append(entry)\n'
     '    del _H3_PROMPTS_HOURS[:-24]\n'
     '    _h3_prompts_offloop(h3_prompts_commit_hour, dict(entry))\n'
     '    pipeline_log("ads", "hourly H3 prompts: %s - %s" % (entry["preset"]["name"] or "?", h3_prompts_how(entry)))\n'
     '    return entry\n'
     '\n'
     '\n'
     'def h3_prompts_commit_hour(entry: dict[str, Any]) -> None:\n'
     '    """[h3-prompts] The hour, into the store\'s history; a pin it used is spent.\n'
     '    A worker thread (the loop hands it over)."""\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        hours = [h for h in store.get("history") or [] if h.get("hour") != entry.get("hour")]\n'
     '        taken = _H3_PROMPTS_DRESSED.get(str(entry.get("hour") or ""))\n'
     '        if taken:                                    # a render took the hour before this write\n'
     '            entry["dressed"], entry["dressed_at"] = int(taken[0]), round(float(taken[1]), 6)\n'
     '        hours.append(entry)\n'
     '        store["history"] = hours[-H3_PROMPTS_HISTORY_KEEP:]\n'
     '        pin = store.get("next")\n'
     '        if entry.get("pin") and isinstance(pin, dict) and pin.get("id") == entry["pin"]:\n'
     '            store["next"] = None\n'
     '    try:\n'
     '        h3_prompts_change(fn)\n'
     '    except Exception as exc:  # noqa: BLE001\n'
     '        pipeline_log("ads", "hourly H3 prompts: the hour\'s record was not written (%s)" % type(exc).__name__)\n'
     '\n'
     '\n'
     'def h3_prompts_commit_dressed(hour: str, count: int, at: float) -> None:\n'
     '    """[h3-prompts] A render took the hour\'s words: the count survives a restart,\n'
     '    so a later render with the same brief finds its own hour. A worker thread."""\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        for entry in store.get("history") or []:\n'
     '            if entry.get("hour") == hour:\n'
     '                entry["dressed"], entry["dressed_at"] = int(count), round(float(at), 6)\n'
     '    try:\n'
     '        h3_prompts_change(fn)\n'
     '    except Exception as exc:  # noqa: BLE001\n'
     '        pipeline_log("ads", "hourly H3 prompts: a render\'s claim was not written (%s)" % type(exc).__name__)\n'
     '\n'
     '\n'
     'def h3_prompts_hour_for(text: Any, exact: bool = False) -> dict[str, Any] | None:\n'
     '    """[h3-prompts] Which hour an hourly render belongs to, by its brief: the clip\n'
     "    road hands the brief itself (exact); a queued host or gallery render's\n"
     '    direction ends with it. Of the hours within a day whose brief fits, the\n'
     '    newest for the clip road (it was resolved a moment ago); for a queued one\n'
     '    the oldest no render has taken yet - the queue is first in, first out -\n'
     '    else the one taken last (a retried render). Memory only, no lock."""\n'
     '    words = str(text or "")\n'
     '    if not words:\n'
     '        return None\n'
     '    store = _H3_PROMPTS_MEM[0] if isinstance(_H3_PROMPTS_MEM[0], dict) else {}\n'
     '    now = time.time()\n'
     '    fits: dict[str, dict[str, Any]] = {}\n'
     '    for entry in list(store.get("history") or []) + list(_H3_PROMPTS_HOURS):\n'
     '        goal = str(entry.get("goal") or "") if isinstance(entry, dict) else ""\n'
     '        if not goal or now - _h3_prompts_stamp(entry.get("at"), 0.0) > H3_PROMPTS_FIND_S:\n'
     '            continue\n'
     '        if (words == goal) if exact else words.endswith(goal):\n'
     '            fits[str(entry.get("hour") or "")] = entry\n'
     '    if not fits:\n'
     '        return None\n'
     '    ordered = sorted(fits.values(), key=lambda e: _h3_prompts_stamp(e.get("at"), 0.0))\n'
     '    if exact:\n'
     '        return ordered[-1]\n'
     '\n'
     '    def taken(entry: dict[str, Any]) -> list[float]:\n'
     '        mine = _H3_PROMPTS_DRESSED.get(str(entry.get("hour") or ""))\n'
     '        return mine or [float(entry.get("dressed") or 0), _h3_prompts_stamp(entry.get("dressed_at"), 0.0)]\n'
     '    fresh = [e for e in ordered if not taken(e)[0]]\n'
     '    return fresh[0] if fresh else max(ordered, key=lambda e: taken(e)[1])\n'
     '\n'
     '\n'
     'def h3_prompts_claim(entry: dict[str, Any]) -> None:\n'
     '    """A render took this hour\'s words (on the loop; the count is written off it)."""\n'
     '    hour = str(entry.get("hour") or "")\n'
     '    if not hour:\n'
     '        return\n'
     '    was = _H3_PROMPTS_DRESSED.get(hour) or [float(entry.get("dressed") or 0), 0.0]\n'
     '    _H3_PROMPTS_DRESSED[hour] = [was[0] + 1, time.time()]\n'
     '    while len(_H3_PROMPTS_DRESSED) > 96:\n'
     '        _H3_PROMPTS_DRESSED.pop(next(iter(_H3_PROMPTS_DRESSED)))\n'
     '    _h3_prompts_offloop(h3_prompts_commit_dressed, hour, int(_H3_PROMPTS_DRESSED[hour][0]),\n'
     '                        _H3_PROMPTS_DRESSED[hour][1])\n'
     '\n'
     '\n'
     'def h3_prompts_words(hour: dict[str, Any], road: str, speech: str = "") -> dict[str, Any]:\n'
     '    """[h3-prompts] What one road of the hour is told - the direction, the line,\n'
     '    the style, the audio direction and constraints - and so the record of it\n'
     '    that rides the render\'s generation row (`h3_prompts`)."""\n'
     '    fields = h3_prompts_fields(hour.get("fields"))\n'
     '    road = road if road in H3_PROMPTS_ROADS else "clip"\n'
     '    values = {"conversation": str(hour.get("conversation") or ""), "record": str(hour.get("record") or ""),\n'
     '              "goal": str(hour.get("goal") or "")}\n'
     '    line = h3_prompts_fill(fields["speech"], **values) if fields["speech"] else str(speech or "")\n'
     '    return {"hour": str(hour.get("hour") or ""), "marker": hour.get("marker"), "at": hour.get("at"),\n'
     '            "how": hour.get("how"), "preset": dict(hour.get("preset") or {}), "roll": hour.get("roll"),\n'
     '            "road": road, "fields": fields, "conversation": values["conversation"],\n'
     '            "record": values["record"], "goal": values["goal"],\n'
     '            "direction": h3_prompts_fill(fields[road], **values)[:1800] or values["goal"],\n'
     '            "speech": " ".join(line.split())[:700], "style": fields["style"],\n'
     '            "constraints": fields["constraints"], "audio_direction": fields["audio_direction"]}\n'
     '\n'
     '\n'
     'def h3_prompts_payload_keys(words: dict[str, Any] | None) -> dict[str, Any]:\n'
     '    """The keys a render payload carries for the hour\'s words: the style term,\n'
     '    the audio direction and constraints (h3_prompts_compose), and the record."""\n'
     '    if not isinstance(words, dict):\n'
     '        return {}\n'
     '    out: dict[str, Any] = {"h3_prompts": words}\n'
     '    if words.get("style"):\n'
     '        out["style"] = words["style"]\n'
     '    brief = {k: words[k] for k in ("constraints", "audio_direction") if words.get(k)}\n'
     '    if brief:\n'
     '        out["h3_brief"] = brief\n'
     '    return out\n'
     '\n'
     '\n'
     'def h3_prompts_dress(payload: Any) -> Any:\n'
     '    """[h3-prompts] A render the hourly door queued for the host\'s or a gallery\n'
     "    picture's road takes the hour's preset at dispatch: that road's direction,\n"
     '    the line, style, audio direction and constraints - and the record of them.\n'
     '    A payload already dressed (the clip road dresses itself in\n'
     '    voice_ad_render), or not hourly, or whose hour is not found, passes as it\n'
     '    is."""\n'
     '    if not isinstance(payload, dict) or not payload.get("hourly") or payload.get("h3_prompts"):\n'
     '        return payload\n'
     '    hour = h3_prompts_hour_for(payload.get("prompt"))\n'
     '    if hour is None:\n'
     '        return payload\n'
     '    road = ("host" if str(payload.get("mode") or "") == "text"\n'
     '            else "gallery" if str(payload.get("source_type") or "") == "gallery" else "clip")\n'
     '    words = h3_prompts_words(hour, road, str(payload.get("speech") or ""))\n'
     '    h3_prompts_claim(hour)\n'
     '    out = dict(payload)\n'
     '    out["prompt"] = words["direction"]\n'
     '    out["speech"] = words["speech"]\n'
     '    out.update(h3_prompts_payload_keys(words))\n'
     '    return out\n'
     '\n'
     '\n'
     'def h3_prompts_compose(brief: Any, *args: Any, **kwargs: Any) -> str:\n'
     '    """[h3-prompts] compose_prompt, with a preset\'s own audio direction and\n'
     "    constraints in place of the gear's brief for this one prompt. Synchronous,\n"
     '    on the event loop: nothing else reads the brief while it is lent."""\n'
     '    over = ({k: " ".join(str(brief.get(k) or "").split())[:400] for k in ("constraints", "audio_direction")}\n'
     '            if isinstance(brief, dict) else {})\n'
     '    over = {k: v for k, v in over.items() if v}\n'
     '    if not over:\n'
     '        return comfy_workshop.compose_prompt(*args, **kwargs)\n'
     '    kept = dict(comfy_workshop.BRIEF)\n'
     '    comfy_workshop.BRIEF.update(over)\n'
     '    try:\n'
     '        return comfy_workshop.compose_prompt(*args, **kwargs)\n'
     '    finally:\n'
     '        comfy_workshop.BRIEF.clear()\n'
     '        comfy_workshop.BRIEF.update(kept)\n'
     '\n'
     '\n'
     'def _h3_prompts_hour_view(entry: dict[str, Any]) -> dict[str, Any]:\n'
     '    return {"hour": entry.get("hour"), "at": entry.get("at"), "marker": entry.get("marker"),\n'
     '            "how": entry.get("how"), "how_words": h3_prompts_how(entry), "preset": entry.get("preset") or {},\n'
     '            "roll": entry.get("roll"), "goal": str(entry.get("goal") or "")[:1200],\n'
     '            "conversation": str(entry.get("conversation") or "")[:600],\n'
     '            "fields": entry.get("fields") if isinstance(entry.get("fields"), dict) else {}}\n'
     '\n'
     '\n'
     'def _h3_prompts_hours(store: dict[str, Any]) -> list[dict[str, Any]]:\n'
     '    """The store\'s hours and any this process resolved but has not written yet, oldest first."""\n'
     '    hours = [h for h in store.get("history") or [] if isinstance(h, dict)]\n'
     '    known = {h.get("hour") for h in hours}\n'
     '    return hours + [h for h in list(_H3_PROMPTS_HOURS) if h.get("hour") not in known]\n'
     '\n'
     '\n'
     'def h3_prompts_next_hour(store: dict[str, Any]) -> dict[str, Any]:\n'
     '    """What the next hour will be told, as far as it is known before its roll."""\n'
     '    presets = store["presets"]\n'
     '    active = next((p for p in presets if p["id"] == store.get("active")), presets[0])\n'
     '    pin = store.get("next")\n'
     '    if isinstance(pin, dict) and isinstance(pin.get("preset"), dict):\n'
     '        name = next((p["name"] for p in presets if pin.get("preset_id") and p["id"] == pin.get("preset_id")),\n'
     '                    str(pin["preset"].get("name") or "pinned words"))\n'
     '        return {"how": "next", "preset": {"id": pin.get("preset_id") or "", "name": name},\n'
     '                "words": \'"%s", pinned for the next hour\' % name}\n'
     '    if store.get("dice") and len(presets) > 1:\n'
     '        return {"how": "dice", "preset": None,\n'
     '                "words": "rolls at the hour among the %d saved presets" % len(presets)}\n'
     '    return {"how": "active", "preset": {"id": active["id"], "name": active["name"]},\n'
     '            "words": \'"%s", the active preset\' % active["name"]}\n'
     '\n'
     '\n'
     'def h3_prompts_view(summary: bool = False) -> dict[str, Any]:\n'
     '    """[h3-prompts] What the gallery\'s P and dice show, and the prompts screen:\n'
     '    the presets, the active one, the dice, the pin, the next and the last hour,\n'
     '    each preset\'s odds on the desk. A worker thread (it may read the disk)."""\n'
     '    store = h3_prompts_load()\n'
     '    presets = store["presets"]\n'
     '    active = next((p for p in presets if p["id"] == store["active"]), presets[0])\n'
     '    hours = _h3_prompts_hours(store)\n'
     '    pin = store.get("next")\n'
     '    out: dict[str, Any] = {\n'
     '        "rev": store.get("rev", 0), "active": active["id"], "active_name": active["name"],\n'
     '        "dice": bool(store.get("dice")), "dice_live": _s3_dice_live(), "count": len(presets),\n'
     '        "next": ({"id": pin.get("id"), "at": pin.get("at"), "from": pin.get("from"),\n'
     '                  "prompt_id": pin.get("prompt_id"), "preset_id": pin.get("preset_id"),\n'
     '                  "name": str((pin.get("preset") or {}).get("name") or "")} if isinstance(pin, dict) else None),\n'
     '        "next_hour": h3_prompts_next_hour(store),\n'
     '        "last_hour": _h3_prompts_hour_view(hours[-1]) if hours else None,\n'
     '        "dice_key": H3_PROMPTS_DICE_KEY}\n'
     '    if summary:\n'
     '        return out\n'
     '    live = out["dice_live"]\n'
     '    desk = h3_prompts_desk() if live else None\n'
     '    weights = h3_prompts_weights(presets, desk) if live else [1.0] * len(presets)\n'
     '    total = sum(weights)\n'
     '    on_desk = {" ".join(str(i.get("text") or "").split()) for i in (desk or {}).get("items") or []\n'
     '               if isinstance(i, dict)}\n'
     '    out.update({\n'
     '        "presets": presets,\n'
     '        "odds": [{"id": p["id"], "weight": round(w, 3), "share": round(100.0 * w / total, 1) if total > 0 else 0.0,\n'
     '                  "on_desk": p["name"] in on_desk, "off": w <= 0} for p, w in zip(presets, weights)],\n'
     '        "desk_tabled": desk is not None, "defaults": dict(H3_PROMPTS_DEFAULT),\n'
     '        "fields": list(H3_PROMPTS_FIELDS), "limits": dict(H3_PROMPTS_LIMITS), "most": H3_PROMPTS_MOST,\n'
     '        "placeholders": {"conversation": "the hour\'s talk - the last lines said on air",\n'
     '                         "record": "the record on air", "goal": "the brief, filled"},\n'
     '        "hours": [_h3_prompts_hour_view(h) for h in hours[-12:]][::-1]})\n'
     '    return out\n'
     '\n'
     '\n'
     'def h3_prompts_history(limit: int = 48) -> dict[str, Any]:\n'
     '    """[h3-prompts] What each hour used, newest first, with the video(s) it made\n'
     '    (the generation rows that carry the hour). A worker thread."""\n'
     '    store = h3_prompts_load()\n'
     '    hours = _h3_prompts_hours(store)[-max(1, min(H3_PROMPTS_HISTORY_KEEP, int(limit or 48))):]\n'
     '    made: dict[str, list[dict[str, Any]]] = {}\n'
     '    try:\n'
     '        for row in _read_all_generations():\n'
     '            rec = row.get("h3_prompts") if isinstance(row, dict) else None\n'
     '            if isinstance(rec, dict) and rec.get("hour"):\n'
     '                made.setdefault(str(rec["hour"]), []).append(\n'
     '                    {"prompt_id": row.get("prompt_id"), "files": row.get("files") or [],\n'
     '                     "status": row.get("status"), "road": rec.get("road"), "ts": row.get("ts")})\n'
     '    except Exception as exc:  # noqa: BLE001\n'
     '        pipeline_log("ads", "hourly H3 prompts: the gallery rows could not be read (%s)" % type(exc).__name__)\n'
     '    return {"hours": [dict(_h3_prompts_hour_view(h), videos=made.get(str(h.get("hour") or ""), []))\n'
     '                      for h in reversed(hours)]}\n'
     '\n'
     '\n'
     'def _h3_prompts_find(store: dict[str, Any], pid: str) -> dict[str, Any]:\n'
     '    got = next((p for p in store["presets"] if p["id"] == pid), None)\n'
     '    if got is None:\n'
     '        raise HTTPException(status_code=404, detail="No preset %s - it may have been deleted" % str(pid)[:40])\n'
     '    return got\n'
     '\n'
     '\n'
     'def _h3_prompts_name_free(store: dict[str, Any], name: str, pid: str = "") -> None:\n'
     '    if any(p["name"].lower() == name.lower() and p["id"] != pid for p in store["presets"]):\n'
     '        raise HTTPException(status_code=409, detail=\'A preset is already called "%s"\' % name)\n'
     '\n'
     '\n'
     'def h3_prompts_from_generation(prompt_id: str) -> dict[str, Any]:\n'
     '    """[h3-prompts] The words a video was made with, as a preset\'s fields: the\n'
     '    preset it recorded (`h3_prompts`), else - a video from before the presets -\n'
     '    the direction and line it was sent, as every road\'s direction."""\n'
     '    row = workshop_generation(str(prompt_id or ""))\n'
     '    if row is None:\n'
     '        raise HTTPException(status_code=404, detail="No such video")\n'
     '    rec = row.get("h3_prompts")\n'
     '    if isinstance(rec, dict) and isinstance(rec.get("fields"), dict):\n'
     '        out: dict[str, Any] = dict(h3_prompts_fields(rec["fields"]))\n'
     '        out["name"] = str((rec.get("preset") or {}).get("name") or "")\n'
     '        return out\n'
     '    direction = _h3_prompts_text(row.get("request") or "", "clip")\n'
     '    if not direction:\n'
     '        raise HTTPException(status_code=409, detail="This video recorded no prompt to reuse")\n'
     '    out = dict(H3_PROMPTS_DEFAULT)\n'
     '    out.update({"clip": direction, "gallery": direction, "host": direction,\n'
     '                "speech": _h3_prompts_text(row.get("speech") or "", "speech")})\n'
     '    stem = Path(str((row.get("files") or [""])[0] or "")).stem\n'
     '    out["name"] = "From " + (stem or str(prompt_id)[:8])\n'
     '    return out\n'
     '\n'
     '\n'
     'def h3_prompts_create(body: dict[str, Any]) -> dict[str, Any]:\n'
     '    """[h3-prompts] A new preset from the words given - or from the words a video\n'
     '    was made with (`from_prompt_id`) - active at once when `activate`."""\n'
     '    raw = dict(body)\n'
     '    if body.get("from_prompt_id"):\n'
     '        raw = h3_prompts_from_generation(str(body["from_prompt_id"]))\n'
     '        if str(body.get("name") or "").strip():\n'
     '            raw["name"] = body["name"]\n'
     '    name = _h3_prompts_text(raw.get("name"), "name")\n'
     '    if not name:\n'
     '        raise HTTPException(status_code=400, detail="Name the preset")\n'
     '    made: dict[str, str] = {}\n'
     '\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        if len(store["presets"]) >= H3_PROMPTS_MOST:\n'
     '            raise HTTPException(status_code=409, detail="%d presets is the most the store keeps - delete one first"\n'
     '                                % H3_PROMPTS_MOST)\n'
     '        _h3_prompts_name_free(store, name)\n'
     '        one = _h3_prompts_preset(dict(raw, name=name, created_at=None, updated_at=None),\n'
     '                                 "p-" + uuid.uuid4().hex[:10])\n'
     '        store["presets"].append(one)\n'
     '        if body.get("activate"):\n'
     '            store["active"] = one["id"]\n'
     '        made["id"] = one["id"]\n'
     '    h3_prompts_change(fn)\n'
     '    pipeline_log("ads", \'hourly H3 prompts: preset "%s" saved\' % name)\n'
     '    return dict(h3_prompts_view(), saved=made.get("id"))\n'
     '\n'
     '\n'
     'def h3_prompts_update(pid: str, body: dict[str, Any]) -> dict[str, Any]:\n'
     '    """[h3-prompts] Change a preset\'s name or words. `was` (the updated_at the\n'
     '    editor loaded) refuses a save over a newer one."""\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        one = _h3_prompts_find(store, pid)\n'
     '        if body.get("was") not in (None, ""):\n'
     '            if abs(_h3_prompts_stamp(body.get("was"), -1.0) - float(one.get("updated_at") or 0)) > 0.002:\n'
     '                raise HTTPException(status_code=409, detail="This preset was changed elsewhere since it was "\n'
     '                                                            "opened - reload it before saving")\n'
     '        if "name" in body:\n'
     '            name = _h3_prompts_text(body.get("name"), "name")\n'
     '            if not name:\n'
     '                raise HTTPException(status_code=400, detail="Name the preset")\n'
     '            _h3_prompts_name_free(store, name, pid)\n'
     '            one["name"] = name\n'
     '        merged = dict(one)\n'
     '        merged.update({f: body[f] for f in H3_PROMPTS_FIELDS if f in body})\n'
     '        one.update(h3_prompts_fields(merged))\n'
     '        one["updated_at"] = round(time.time(), 3)\n'
     '    h3_prompts_change(fn)\n'
     '    return dict(h3_prompts_view(), saved=pid)\n'
     '\n'
     '\n'
     'def h3_prompts_delete(pid: str) -> dict[str, Any]:\n'
     '    """[h3-prompts] Delete a preset - never the last: the hourly render needs\n'
     '    words. The active one moves to the first left."""\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        _h3_prompts_find(store, pid)\n'
     '        if len(store["presets"]) <= 1:\n'
     '            raise HTTPException(status_code=409, detail="The last preset stays - the hourly render needs words")\n'
     '        store["presets"] = [p for p in store["presets"] if p["id"] != pid]\n'
     '        if store["active"] == pid:\n'
     '            store["active"] = store["presets"][0]["id"]\n'
     '    h3_prompts_change(fn)\n'
     '    return h3_prompts_view()\n'
     '\n'
     '\n'
     'def h3_prompts_activate(pid: str) -> dict[str, Any]:\n'
     '    """[h3-prompts] The preset every hour uses while the dice are off."""\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        _h3_prompts_find(store, pid)\n'
     '        store["active"] = pid\n'
     '    h3_prompts_change(fn)\n'
     '    return h3_prompts_view()\n'
     '\n'
     '\n'
     'def h3_prompts_dice(on: bool) -> dict[str, Any]:\n'
     '    """[h3-prompts] The gallery\'s dice: on, each hour\'s preset is System 3\'s roll\n'
     '    among the saved presets; off, the active preset. Turned on, the presets are\n'
     '    put on the desk (the dice door tables the POOLS1 row) so they can be weighted\n'
     '    before the first roll."""\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        store["dice"] = bool(on)\n'
     '    store = h3_prompts_change(fn)\n'
     '    if on and _s3_dice_live():\n'
     '        try:\n'
     '            s3_pool(H3_PROMPTS_DICE_KEY, [p["name"] for p in store["presets"]], H3_PROMPTS_DICE_LABEL)\n'
     '        except Exception:  # noqa: BLE001 - the desk row is a convenience; the roll tables it anyway\n'
     '            pass\n'
     '    pipeline_log("ads", "hourly H3 prompts: the dice %s" % ("on" if on else "off"))\n'
     '    return h3_prompts_view()\n'
     '\n'
     '\n'
     'def h3_prompts_pin(body: dict[str, Any]) -> dict[str, Any]:\n'
     '    """[h3-prompts] The words the next hour uses, once: a saved preset\n'
     '    (`preset_id`), words from the editor (`preset`), the words a video was made\n'
     '    with (`from_prompt_id`) - or none (`clear`)."""\n'
     '    pin: dict[str, Any] | None = None\n'
     '    if not body.get("clear"):\n'
     '        now = round(time.time(), 3)\n'
     '        if body.get("from_prompt_id"):\n'
     '            words = h3_prompts_from_generation(str(body["from_prompt_id"]))\n'
     '            pin = {"from": "video", "prompt_id": str(body["from_prompt_id"])[:120],\n'
     '                   "preset": _h3_prompts_preset(dict(words, name=words.get("name") or "A video\'s words"), "pinned")}\n'
     '        elif isinstance(body.get("preset"), dict):\n'
     '            raw = body["preset"]\n'
     '            pin = {"from": "editor", "preset": _h3_prompts_preset(\n'
     '                dict(raw, name=_h3_prompts_text(raw.get("name"), "name") or "Pinned words"), "pinned")}\n'
     '        elif body.get("preset_id"):\n'
     '            pin = {"from": "preset", "preset_id": str(body["preset_id"])[:40]}\n'
     '        else:\n'
     '            raise HTTPException(status_code=400, detail="Pin a preset_id, a preset or a from_prompt_id - or clear")\n'
     '        pin.update({"id": "n-" + uuid.uuid4().hex[:10], "at": now})\n'
     '\n'
     '    def fn(store: dict[str, Any]) -> None:\n'
     '        if pin is not None and pin.get("preset_id"):\n'
     '            pin["preset"] = copy.deepcopy(_h3_prompts_find(store, pin["preset_id"]))\n'
     '        store["next"] = pin\n'
     '    h3_prompts_change(fn)\n'
     '    pipeline_log("ads", "hourly H3 prompts: the next hour %s" % (\n'
     '        \'uses "%s"\' % pin["preset"]["name"] if pin else "is unpinned"))\n'
     '    return h3_prompts_view()\n'
     '\n'
     '\n'
     'async def _h3_prompts_body(request: Request) -> dict[str, Any]:\n'
     '    try:\n'
     '        payload = await request.json()\n'
     '    except Exception:  # noqa: BLE001\n'
     '        payload = None\n'
     '    if not isinstance(payload, dict):\n'
     '        raise HTTPException(status_code=400, detail="Expected an object")\n'
     '    return payload\n'
     '\n'
     '\n'
     '@app.get("/api/h3/prompts")\n'
     'async def h3_prompts_get(summary: int = 0, authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] The hourly prompts: the presets, the active one, the dice,\n'
     "    the pin, the next and last hour (summary=1: only the state the gallery's\n"
     '    P and dice show)."""\n'
     '    require_read_auth(authorization)\n'
     '    return await asyncio.to_thread(h3_prompts_view, bool(summary))\n'
     '\n'
     '\n'
     '@app.get("/api/h3/prompts/history")\n'
     'async def h3_prompts_history_get(limit: int = 48, authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] What each hour used, newest first, with the video it made."""\n'
     '    require_read_auth(authorization)\n'
     '    return await asyncio.to_thread(h3_prompts_history, limit)\n'
     '\n'
     '\n'
     '@app.post("/api/h3/prompts/active")\n'
     'async def h3_prompts_active_set(request: Request, authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] {id}: the preset every hour uses while the dice are off."""\n'
     '    require_auth(authorization)\n'
     '    body = await _h3_prompts_body(request)\n'
     '    return await asyncio.to_thread(h3_prompts_activate, str(body.get("id") or ""))\n'
     '\n'
     '\n'
     '@app.post("/api/h3/prompts/dice")\n'
     'async def h3_prompts_dice_set(request: Request, authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] {on}: the gallery\'s dice."""\n'
     '    require_auth(authorization)\n'
     '    body = await _h3_prompts_body(request)\n'
     '    return await asyncio.to_thread(h3_prompts_dice, bool(body.get("on")))\n'
     '\n'
     '\n'
     '@app.post("/api/h3/prompts/next")\n'
     'async def h3_prompts_next_set(request: Request, authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] {preset_id} | {preset} | {from_prompt_id} | {clear}: the\n'
     '    words the next hour uses, once."""\n'
     '    require_auth(authorization)\n'
     '    body = await _h3_prompts_body(request)\n'
     '    return await asyncio.to_thread(h3_prompts_pin, body)\n'
     '\n'
     '\n'
     '@app.post("/api/h3/prompts")\n'
     'async def h3_prompts_create_api(request: Request, authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] {name, goal, clip, gallery, host, speech, style, constraints,\n'
     '    audio_direction, activate?} or {from_prompt_id, name?}: a new preset."""\n'
     '    require_auth(authorization)\n'
     '    body = await _h3_prompts_body(request)\n'
     '    return await asyncio.to_thread(h3_prompts_create, body)\n'
     '\n'
     '\n'
     '@app.post("/api/h3/prompts/{pid}")\n'
     'async def h3_prompts_update_api(pid: str, request: Request,\n'
     '                                authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] {name?, <fields>?, was?}: change a preset."""\n'
     '    require_auth(authorization)\n'
     '    body = await _h3_prompts_body(request)\n'
     '    return await asyncio.to_thread(h3_prompts_update, pid[:40], body)\n'
     '\n'
     '\n'
     '@app.post("/api/h3/prompts/{pid}/delete")\n'
     'async def h3_prompts_delete_api(pid: str, authorization: str | None = Header(default=None)) -> dict[str, Any]:\n'
     '    """[h3-prompts] Delete a preset (never the last)."""\n'
     '    require_auth(authorization)\n'
     '    return await asyncio.to_thread(h3_prompts_delete, pid[:40])\n'
     '\n'
     '\n'
     '@app.on_event("startup")\n'
     'async def _h3_prompts_start() -> None:\n'
     '    """[h3-prompts] The store into memory before the first hour - off the loop."""\n'
     '    try:\n'
     '        await asyncio.to_thread(h3_prompts_load)\n'
     '    except Exception as exc:  # noqa: BLE001\n'
     '        pipeline_log("ads", "hourly H3 prompt presets not loaded (%s)" % type(exc).__name__)\n'
     '\n'
     '\n'
     '@app.on_event("startup")\n'
     'async def _parody_stinger_start() -> None:\n', 1),
]


def plan(text):
    return list(EDITS)


def state_of(text, old, new, count):
    n_new = text.count(new)
    n_old = text.count(old)
    if n_new >= 1 and n_old == new.count(old) * n_new:
        return "applied"
    if n_new == 0 and n_old == count:
        return "ready"
    return "anchor found %d times, wanted %d; replacement found %d times" % (n_old, count, n_new)


def check(text):
    applied, missing = 0, []
    for name, old, new, count in plan(text):
        state = state_of(text, old, new, count)
        if state == "applied":
            applied += 1
        elif state != "ready":
            missing.append("%s (%s)" % (name, state))
    return applied, missing


def apply(path):
    path = Path(path)
    text = path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    applied, missing = check(text)
    edits = plan(text)
    if applied == len(edits):
        return 2
    if missing:
        for m in missing:
            print("missing:", m)
        return 1
    for name, old, new, count in edits:
        if state_of(text, old, new, count) == "applied":
            continue
        assert text.count(old) == count, "%s: anchor found %d times" % (name, text.count(old))
        text = text.replace(old, new)
    assert "\r" not in text
    fd, tmp = tempfile.mkstemp(prefix=path.name + ".", dir=str(path.parent))
    with os.fdopen(fd, "wb") as fh:
        fh.write(text.encode("utf-8"))
    os.replace(tmp, path)
    return 0


def main(argv):
    do_apply = "--apply" in argv
    target = next((a for a in argv if not a.startswith("--")), "app.py")
    if do_apply:
        code = apply(target)
        print({0: "APPLIED", 1: "ANCHORS MISSING - nothing written", 2: "already applied"}[code])
        return code
    text = Path(target).read_bytes().decode("utf-8").replace("\r\n", "\n")
    applied, missing = check(text)
    total = len(plan(text))
    if missing:
        for m in missing:
            print("missing:", m)
        print("%d of %d applied" % (applied, total))
        return 1
    if applied == total:
        print("already applied (%d edits)" % total)
        return 2
    print("ready: %d edits, %d already in" % (total, applied))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
